<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>6&nbsp; Block II Unit 1 – BA for Agriculture</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./block-II-unit-2.html" rel="next">
<link href="./block-I-unit-2.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-7f8f88aac4f3542376d5c11b86a4c14d.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-9e3e5b9121e68b3f077afb32f2c64d95.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./block-II-unit-1.html"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Block II Unit 1</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">BA for Agriculture</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Know Your Instructor</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./syllabus.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Syllabus</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./schedule.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Schedule</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./block-I-unit-1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Block I Unit 1</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./block-I-unit-2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Block I Unit 2</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./block-II-unit-1.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Block II Unit 1</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./block-II-unit-2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Block II Unit 2</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./block-II-unit-3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Block II Unit 3</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./projects.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Projects</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#supervised-machine-learning-basic-framework-regression-models-and-classification-models" id="toc-supervised-machine-learning-basic-framework-regression-models-and-classification-models" class="nav-link active" data-scroll-target="#supervised-machine-learning-basic-framework-regression-models-and-classification-models"><span class="header-section-number">6.1</span> Supervised machine learning: Basic framework, regression models and classification models</a></li>
  <li><a href="#types-of-machine-learning" id="toc-types-of-machine-learning" class="nav-link" data-scroll-target="#types-of-machine-learning"><span class="header-section-number">6.2</span> Types of machine learning</a>
  <ul class="collapse">
  <li><a href="#supervised-learning" id="toc-supervised-learning" class="nav-link" data-scroll-target="#supervised-learning"><span class="header-section-number">6.2.1</span> Supervised learning</a></li>
  </ul></li>
  <li><a href="#machine-learning-case-study" id="toc-machine-learning-case-study" class="nav-link" data-scroll-target="#machine-learning-case-study"><span class="header-section-number">6.3</span> Machine Learning Case Study</a>
  <ul class="collapse">
  <li><a href="#build-a-baseline-model" id="toc-build-a-baseline-model" class="nav-link" data-scroll-target="#build-a-baseline-model"><span class="header-section-number">6.3.1</span> Build a Baseline Model</a></li>
  </ul></li>
  <li><a href="#data-pre-processing" id="toc-data-pre-processing" class="nav-link" data-scroll-target="#data-pre-processing"><span class="header-section-number">6.4</span> Data Pre-Processing</a>
  <ul class="collapse">
  <li><a href="#data-split" id="toc-data-split" class="nav-link" data-scroll-target="#data-split"><span class="header-section-number">6.4.1</span> Data Split</a></li>
  <li><a href="#build-the-preprocessing-recipe" id="toc-build-the-preprocessing-recipe" class="nav-link" data-scroll-target="#build-the-preprocessing-recipe"><span class="header-section-number">6.4.2</span> Build the preprocessing <code>recipe</code></a></li>
  <li><a href="#inspect-the-recipe-without-training-a-model" id="toc-inspect-the-recipe-without-training-a-model" class="nav-link" data-scroll-target="#inspect-the-recipe-without-training-a-model"><span class="header-section-number">6.4.3</span> Inspect the recipe without training a model</a></li>
  <li><a href="#data-pransformation-for-model" id="toc-data-pransformation-for-model" class="nav-link" data-scroll-target="#data-pransformation-for-model"><span class="header-section-number">6.4.4</span> Data Pransformation for Model</a></li>
  <li><a href="#plug-the-recipe-into-a-modeling-workflow" id="toc-plug-the-recipe-into-a-modeling-workflow" class="nav-link" data-scroll-target="#plug-the-recipe-into-a-modeling-workflow"><span class="header-section-number">6.4.5</span> Plug the recipe into a modeling workflow</a></li>
  <li><a href="#evaluate-on-held-out-test-data" id="toc-evaluate-on-held-out-test-data" class="nav-link" data-scroll-target="#evaluate-on-held-out-test-data"><span class="header-section-number">6.4.6</span> Evaluate on held-out test data</a></li>
  <li><a href="#multiclass-roc-one-vs-rest" id="toc-multiclass-roc-one-vs-rest" class="nav-link" data-scroll-target="#multiclass-roc-one-vs-rest"><span class="header-section-number">6.4.7</span> Multiclass ROC (one-vs-rest)</a></li>
  <li><a href="#concluding-remarks" id="toc-concluding-remarks" class="nav-link" data-scroll-target="#concluding-remarks"><span class="header-section-number">6.4.8</span> Concluding Remarks</a></li>
  </ul></li>
  <li><a href="#regression-methods" id="toc-regression-methods" class="nav-link" data-scroll-target="#regression-methods"><span class="header-section-number">6.5</span> Regression Methods</a>
  <ul class="collapse">
  <li><a href="#simulate-data" id="toc-simulate-data" class="nav-link" data-scroll-target="#simulate-data"><span class="header-section-number">6.5.1</span> Simulate Data</a></li>
  <li><a href="#traintest-split-8020" id="toc-traintest-split-8020" class="nav-link" data-scroll-target="#traintest-split-8020"><span class="header-section-number">6.5.2</span> Train/test split (80/20)</a></li>
  <li><a href="#linear-regression" id="toc-linear-regression" class="nav-link" data-scroll-target="#linear-regression"><span class="header-section-number">6.5.3</span> LINEAR REGRESSION</a></li>
  <li><a href="#multiple-regression" id="toc-multiple-regression" class="nav-link" data-scroll-target="#multiple-regression"><span class="header-section-number">6.5.4</span> MULTIPLE REGRESSION</a></li>
  <li><a href="#polynomial-regression" id="toc-polynomial-regression" class="nav-link" data-scroll-target="#polynomial-regression"><span class="header-section-number">6.5.5</span> POLYNOMIAL REGRESSION</a></li>
  <li><a href="#nonlinear-regression-nls" id="toc-nonlinear-regression-nls" class="nav-link" data-scroll-target="#nonlinear-regression-nls"><span class="header-section-number">6.5.6</span> NONLINEAR REGRESSION (nls)</a></li>
  <li><a href="#stepwise-regression" id="toc-stepwise-regression" class="nav-link" data-scroll-target="#stepwise-regression"><span class="header-section-number">6.5.7</span> STEPWISE REGRESSION</a></li>
  <li><a href="#ridge-regression" id="toc-ridge-regression" class="nav-link" data-scroll-target="#ridge-regression"><span class="header-section-number">6.5.8</span> RIDGE REGRESSION</a></li>
  <li><a href="#lasso-regression" id="toc-lasso-regression" class="nav-link" data-scroll-target="#lasso-regression"><span class="header-section-number">6.5.9</span> LASSO REGRESSION</a></li>
  <li><a href="#quantile-regression" id="toc-quantile-regression" class="nav-link" data-scroll-target="#quantile-regression"><span class="header-section-number">6.5.10</span> QUANTILE REGRESSION</a></li>
  <li><a href="#logistic-regression" id="toc-logistic-regression" class="nav-link" data-scroll-target="#logistic-regression"><span class="header-section-number">6.5.11</span> LOGISTIC REGRESSION</a></li>
  </ul></li>
  <li><a href="#section" id="toc-section" class="nav-link" data-scroll-target="#section"><span class="header-section-number">6.6</span> ============================================================</a></li>
  <li><a href="#summary-when-to-use-which" id="toc-summary-when-to-use-which" class="nav-link" data-scroll-target="#summary-when-to-use-which"><span class="header-section-number">6.7</span> SUMMARY — When to use which</a></li>
  <li><a href="#section-1" id="toc-section-1" class="nav-link" data-scroll-target="#section-1"><span class="header-section-number">6.8</span> ============================================================</a></li>
  <li><a href="#linear---one-predictor-straight-line-relationship" id="toc-linear---one-predictor-straight-line-relationship" class="nav-link" data-scroll-target="#linear---one-predictor-straight-line-relationship"><span class="header-section-number">6.9</span> Linear - one predictor, straight-line relationship</a></li>
  <li><a href="#multiple---several-predictors-each-additivelinear" id="toc-multiple---several-predictors-each-additivelinear" class="nav-link" data-scroll-target="#multiple---several-predictors-each-additivelinear"><span class="header-section-number">6.10</span> Multiple - several predictors, each additive/linear</a></li>
  <li><a href="#polynomial---curved-relationship-still-fit-within-lm-framework" id="toc-polynomial---curved-relationship-still-fit-within-lm-framework" class="nav-link" data-scroll-target="#polynomial---curved-relationship-still-fit-within-lm-framework"><span class="header-section-number">6.11</span> Polynomial - curved relationship still fit within lm() framework</a></li>
  <li><a href="#nonlinearnls--true-nonlinear-functional-form-e.g.-saturation" id="toc-nonlinearnls--true-nonlinear-functional-form-e.g.-saturation" class="nav-link" data-scroll-target="#nonlinearnls--true-nonlinear-functional-form-e.g.-saturation"><span class="header-section-number">6.12</span> Nonlinear(nls)- true nonlinear functional form (e.g.&nbsp;saturation,</a></li>
  <li><a href="#growth-curves---you-must-specify-the-equation" id="toc-growth-curves---you-must-specify-the-equation" class="nav-link" data-scroll-target="#growth-curves---you-must-specify-the-equation"><span class="header-section-number">6.13</span> growth curves) - you must specify the equation</a></li>
  <li><a href="#stepwise---automatic-predictor-selection-via-aic" id="toc-stepwise---automatic-predictor-selection-via-aic" class="nav-link" data-scroll-target="#stepwise---automatic-predictor-selection-via-aic"><span class="header-section-number">6.14</span> Stepwise - automatic predictor selection via AIC</a></li>
  <li><a href="#ridge---manycorrelated-predictors-keep-all-shrink-coefficients" id="toc-ridge---manycorrelated-predictors-keep-all-shrink-coefficients" class="nav-link" data-scroll-target="#ridge---manycorrelated-predictors-keep-all-shrink-coefficients"><span class="header-section-number">6.15</span> Ridge - many/correlated predictors, keep all, shrink coefficients</a></li>
  <li><a href="#lasso---many-predictors-want-automatic-feature-selection" id="toc-lasso---many-predictors-want-automatic-feature-selection" class="nav-link" data-scroll-target="#lasso---many-predictors-want-automatic-feature-selection"><span class="header-section-number">6.16</span> Lasso - many predictors, want automatic feature selection</a></li>
  <li><a href="#quantile---care-about-a-specific-percentile-not-just-the-mean" id="toc-quantile---care-about-a-specific-percentile-not-just-the-mean" class="nav-link" data-scroll-target="#quantile---care-about-a-specific-percentile-not-just-the-mean"><span class="header-section-number">6.17</span> Quantile - care about a specific percentile, not just the mean</a></li>
  <li><a href="#e.g.-worst-casebest-case-yield-planning" id="toc-e.g.-worst-casebest-case-yield-planning" class="nav-link" data-scroll-target="#e.g.-worst-casebest-case-yield-planning"><span class="header-section-number">6.18</span> (e.g.&nbsp;worst-case/best-case yield planning)</a></li>
  <li><a href="#logistic---binary-outcome-successfailure-goodbad-yesno" id="toc-logistic---binary-outcome-successfailure-goodbad-yesno" class="nav-link" data-scroll-target="#logistic---binary-outcome-successfailure-goodbad-yesno"><span class="header-section-number">6.19</span> Logistic - binary outcome (success/failure, good/bad, yes/no)</a></li>
  <li><a href="#section-2" id="toc-section-2" class="nav-link" data-scroll-target="#section-2"><span class="header-section-number">6.20</span> ============================================================</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Block II Unit 1</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="callout callout-style-default callout-note callout-titled" title="Chapter Outline">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Chapter Outline
</div>
</div>
<div class="callout-body-container callout-body">
<p>Supervised machine learning: Basic framework, regression models and classification models. Linear regression, nonlinear regression, multiple regression, polynomial regression,lasso regression, ridge regression, stepwise regression, quantile regression, logistic regression.</p>
</div>
</div>
<section id="supervised-machine-learning-basic-framework-regression-models-and-classification-models" class="level2" data-number="6.1">
<h2 data-number="6.1" class="anchored" data-anchor-id="supervised-machine-learning-basic-framework-regression-models-and-classification-models"><span class="header-section-number">6.1</span> Supervised machine learning: Basic framework, regression models and classification models</h2>
<p>Let’s understand term machine learning. According to Dave Bergmann of IBM, Machine learning is a subset of AI where algorithms learn patterns from training data to make inferences about new data without explicit instructions. This pattern recognition ability enables machine learning models to make decisions or predictions without explicit, hard-coded instructions.</p>
<p><img src="ml.jfif" class="img-fluid"></p>
<p>Though “machine learning” and “artificial intelligence” are often used interchangeably, they are not quite synonymous. In short: all machine learning is AI, but not all AI is machine learning.</p>
<p>Machine learning works through mathematical logic. The relevant characteristics (or “features”) of each data point must therefore be expressed numerically, so that the data itself can be fed into a mathematical algorithm that will “learn” to map a given input to the desired output. The (often manual) process of choosing which aspects of data to use in machine learning algorithms is called feature selection. Feature extraction techniques refine data down to only its most relevant, meaningful dimensions.</p>
</section>
<section id="types-of-machine-learning" class="level2" data-number="6.2">
<h2 data-number="6.2" class="anchored" data-anchor-id="types-of-machine-learning"><span class="header-section-number">6.2</span> Types of machine learning</h2>
<p>All machine learning methods can be categorized as one of three distinct learning paradigms: supervised learning, unsupervised learning or reinforcement learning, based on the nature of their training objectives and (often but not always) by the type of training data they entail.</p>
<p>Supervised learning trains a model to predict the “correct” output for a given input. It applies to tasks that require some degree of accuracy relative to some external “ground truth,” such as classification or regression. Unsupervised learning trains a model to discern intrinsic patterns, dependencies and correlations in data. Unlike in supervised learning, unsupervised learning tasks don’t involve any external ground truth against which its outputs should be compared.</p>
<p>Reinforcement learning (RL) trains a model to evaluate its environment and take an action that will garner the greatest reward. RL scenarios don’t entail the existence of a singular ground truth, but they do entail the existence of “good” and “bad” (or neutral) actions.</p>
<section id="supervised-learning" class="level3" data-number="6.2.1">
<h3 data-number="6.2.1" class="anchored" data-anchor-id="supervised-learning"><span class="header-section-number">6.2.1</span> Supervised learning</h3>
<p>Supervised learning algorithms train models for tasks requiring accuracy, such as classification or regression. Supervised machine learning powers both state-of-the-art deep learning models and a wide array of traditional ML models still widely employed across industries.</p>
<p><em>Regression models</em> predict continuous values, such as price, duration, temperature or size. Examples of traditional regression algorithms include linear regression, polynomial regression and state space models.</p>
<p><em>Classification models</em> predict discrete values, such as the category (or class) a data point belongs to, a binary decision or a specific action to be taken. Examples of traditional classification algorithms include support vector machines (SVMs), Naïve Bayes and logistic regression.</p>
<p>Many supervised ML algorithms can be used for either task. For instance, the output of what’s nominally a regression algorithm can subsequently be used to inform a classification prediction.</p>
</section>
</section>
<section id="machine-learning-case-study" class="level2" data-number="6.3">
<h2 data-number="6.3" class="anchored" data-anchor-id="machine-learning-case-study"><span class="header-section-number">6.3</span> Machine Learning Case Study</h2>
<section id="build-a-baseline-model" class="level3" data-number="6.3.1">
<h3 data-number="6.3.1" class="anchored" data-anchor-id="build-a-baseline-model"><span class="header-section-number">6.3.1</span> Build a Baseline Model</h3>
<p><img src="sea.webp" class="img-fluid"></p>
<p>Credit: https://share.google/VZsjc4wcgbifTAUZd</p>
<p><img src="food.webp" class="img-fluid"></p>
<p>Credit: https://share.google/GJPqwS4zBoWp9Ej25</p>
<p>A Japanese company - selling packed sea urchin based food preps. Recently Japanese Food Regulation Authority made sea urchin based food manufacturing more stringent and adherence to nutritional consistency more stringent.</p>
<p>Till now, company was receiving sea urchin supplies from local fishermen. Company washes, preserves and packages the sea urchins and sends in the market. In this process, the sea urchin’s nutritional values were not managed by company as they just collect and market them. Due to difference in quality, there were various voices raised by the food experts so that people get consistent quality.</p>
<p>Company management decides to introduce a 30 day feed plan for the supplies of the sea urchins before they are packed and sent to the market. So, they wanted an real world evidence of a diet plan that can make sea urchins width equal and consistent. The company wants to calibrate width and initial volume vs.&nbsp;the food regime. The data collected is shown below:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidymodels)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'tidymodels' was built under R version 4.4.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching packages ────────────────────────────────────── tidymodels 1.3.0 ──</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>✔ broom        1.0.7     ✔ recipes      1.3.1
✔ dials        1.4.0     ✔ rsample      1.3.1
✔ dplyr        1.2.1     ✔ tibble       3.2.1
✔ ggplot2      3.5.2     ✔ tidyr        1.3.2
✔ infer        1.0.7     ✔ tune         2.0.1
✔ modeldata    1.4.0     ✔ workflows    1.3.0
✔ parsnip      1.3.2     ✔ workflowsets 1.1.0
✔ purrr        1.0.4     ✔ yardstick    1.3.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'broom' was built under R version 4.4.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'dials' was built under R version 4.4.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'dplyr' was built under R version 4.4.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'ggplot2' was built under R version 4.4.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'infer' was built under R version 4.4.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'modeldata' was built under R version 4.4.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'parsnip' was built under R version 4.4.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'purrr' was built under R version 4.4.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'recipes' was built under R version 4.4.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'rsample' was built under R version 4.4.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'tidyr' was built under R version 4.4.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'tune' was built under R version 4.4.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'workflows' was built under R version 4.4.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'workflowsets' was built under R version 4.4.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'yardstick' was built under R version 4.4.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>── Conflicts ───────────────────────────────────────── tidymodels_conflicts() ──
✖ purrr::discard() masks scales::discard()
✖ dplyr::filter()  masks stats::filter()
✖ dplyr::lag()     masks stats::lag()
✖ recipes::step()  masks stats::step()</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readr)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'readr'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:yardstick':

    spec</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:scales':

    col_factor</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>urchins <span class="ot">&lt;-</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">read_csv</span>(<span class="st">"https://tidymodels.org/start/models/urchins.csv"</span>) <span class="sc">|&gt;</span></span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">setNames</span>(<span class="fu">c</span>(<span class="st">"food_regime"</span>, <span class="st">"initial_volume"</span>, <span class="st">"width"</span>)) <span class="sc">|&gt;</span> </span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">food_regime =</span> <span class="fu">factor</span>(food_regime, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"Initial"</span>, <span class="st">"Low"</span>, <span class="st">"High"</span>)))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 72 Columns: 3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (1): TREAT
dbl (2): IV, SUTW

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(urchins)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 3
  food_regime initial_volume width
  &lt;fct&gt;                &lt;dbl&gt; &lt;dbl&gt;
1 Initial                3.5 0.01 
2 Initial                5   0.02 
3 Initial                8   0.061
4 Initial               10   0.051
5 Initial               13   0.041
6 Initial               13   0.061</code></pre>
</div>
</div>
<p>To keep the diet regime composition secret, company codifies the three levels of diets as Initial, Low and High. Number of observations in the data is 72.</p>
<p>Let’s plot the data:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(urchins,</span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>       </span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>       <span class="fu">aes</span>(<span class="at">x=</span>initial_volume, <span class="at">y=</span>width, <span class="at">colour =</span> food_regime)) <span class="sc">+</span></span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a>      <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb30-8"><a href="#cb30-8" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb30-9"><a href="#cb30-9" aria-hidden="true" tabindex="-1"></a>      <span class="fu">geom_smooth</span>(<span class="at">method =</span> lm, <span class="at">se =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb30-10"><a href="#cb30-10" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb30-11"><a href="#cb30-11" aria-hidden="true" tabindex="-1"></a>      <span class="fu">labs</span>(<span class="at">title=</span><span class="st">"Sea Urchin: Width Vs initial volume"</span>,</span>
<span id="cb30-12"><a href="#cb30-12" aria-hidden="true" tabindex="-1"></a>           <span class="at">y =</span> <span class="st">"Width"</span>,</span>
<span id="cb30-13"><a href="#cb30-13" aria-hidden="true" tabindex="-1"></a>           <span class="at">x =</span> <span class="st">"initial volume"</span>,</span>
<span id="cb30-14"><a href="#cb30-14" aria-hidden="true" tabindex="-1"></a>           <span class="at">subtitle =</span> <span class="st">"Based on sample of 72 urchins"</span>,</span>
<span id="cb30-15"><a href="#cb30-15" aria-hidden="true" tabindex="-1"></a>           <span class="at">caption =</span> <span class="st">"Study conducted by IABM Students MBA Part 2"</span>) <span class="sc">+</span></span>
<span id="cb30-16"><a href="#cb30-16" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb30-17"><a href="#cb30-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="block-II-unit-1_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>If we observe the plot, we can see that food regime has different effect for the width vs initial volume relationship. This gives us an indication that food regime interacts with width and initial volume relationship. This a significant information for building a machine learning model. Since the slopes appear to be different for at least two of the feeding regimes, let’s build a model that allows for two-way interactions. Specifying an R formula with our variables in this way:</p>
<p><code>width ~ initial_volume * food_regime</code></p>
<p>We can also check the distribution of width and initial volume acorss the sample:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(urchins<span class="sc">$</span>width, <span class="at">main=</span><span class="st">"Distribution of width : Sea Urchin"</span>, <span class="at">n=</span><span class="dv">30</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="block-II-unit-1_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(urchins<span class="sc">$</span>initial_volume, <span class="at">main=</span><span class="st">"Distribution of initial volume : Sea Urchin"</span>, <span class="at">n=</span><span class="dv">30</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="block-II-unit-1_files/figure-html/unnamed-chunk-3-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>We can see that the distribution of the width and initial volume of sea urchin sample is near to normal bell shaped curve. We can check normality of a variable through statistical tests also:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co"># applying shapiro-Wilk test</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(urchins<span class="sc">$</span>width)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  urchins$width
W = 0.95726, p-value = 0.01552</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(urchins<span class="sc">$</span>initial_volume)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  urchins$initial_volume
W = 0.91466, p-value = 0.0001247</code></pre>
</div>
</div>
<p>To check the assumption of normality, Shapiro-Wilk tests were conducted on the sample of 72 urchins. The results indicated that the distribution of initial volume (W = 0.91, p &lt; .001) and width (W = 0.96, p = .016) both significantly deviated from normality.</p>
<p>Let’s also check for missing values in the data:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">is.na</span>(urchins))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0</code></pre>
</div>
</div>
<p>So, there is no missing values in the dataset.</p>
<p>The width and initial_volume both are numerical variables and we want to predict width based on initial_volume subject to food_regime. This can be modeled with linear regression model. Following command chunck shows this:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>lm_mod <span class="ot">=</span> <span class="fu">linear_reg</span>()</span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>lm_fit <span class="ot">=</span> lm_mod <span class="sc">|&gt;</span></span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">fit</span>(width <span class="sc">~</span> initial_volume <span class="sc">*</span> food_regime, <span class="at">data =</span> urchins)</span>
<span id="cb40-6"><a href="#cb40-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-7"><a href="#cb40-7" aria-hidden="true" tabindex="-1"></a>lm_fit</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>parsnip model object


Call:
stats::lm(formula = width ~ initial_volume * food_regime, data = data)

Coefficients:
                   (Intercept)                  initial_volume  
                     0.0331216                       0.0015546  
                food_regimeLow                 food_regimeHigh  
                     0.0197824                       0.0214111  
 initial_volume:food_regimeLow  initial_volume:food_regimeHigh  
                    -0.0012594                       0.0005254  </code></pre>
</div>
</div>
<p>Let’s see the model in better (tidy) format:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(lm_fit)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 5
  term                            estimate std.error statistic  p.value
  &lt;chr&gt;                              &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
1 (Intercept)                     0.0331    0.00962      3.44  0.00100 
2 initial_volume                  0.00155   0.000398     3.91  0.000222
3 food_regimeLow                  0.0198    0.0130       1.52  0.133   
4 food_regimeHigh                 0.0214    0.0145       1.47  0.145   
5 initial_volume:food_regimeLow  -0.00126   0.000510    -2.47  0.0162  
6 initial_volume:food_regimeHigh  0.000525  0.000702     0.748 0.457   </code></pre>
</div>
</div>
<p>With <code>dotwhisker</code> package, we can also observe model visually:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dotwhisker)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'dotwhisker' was built under R version 4.4.3</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(lm_fit) <span class="sc">|&gt;</span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">dwplot</span>(<span class="at">dot_args =</span> <span class="fu">list</span>(<span class="at">size =</span> <span class="dv">2</span>, <span class="at">color =</span> <span class="st">"#7C7C7C"</span>),</span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">whisker_args =</span> <span class="fu">list</span>(<span class="at">color =</span> <span class="st">"#7C7C7C"</span>),</span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">vline =</span> <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="dv">0</span>, <span class="at">colour =</span> <span class="st">"grey50"</span>, <span class="at">linetype =</span> <span class="dv">2</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="block-II-unit-1_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Now let’s create new set of observations to predict the width of sea urchin using the regression model we buold just now.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>new_obs <span class="ot">=</span> <span class="fu">expand.grid</span>(<span class="at">initial_volume =</span> <span class="dv">20</span>, </span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>                       <span class="at">food_regime =</span> <span class="fu">c</span>(<span class="st">"Initial"</span>,<span class="st">"Low"</span>,<span class="st">"High"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Let’s predict:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>mean_pred <span class="ot">=</span> <span class="fu">predict</span>(lm_fit, <span class="at">new_data =</span> new_obs)</span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a>mean_pred</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 1
   .pred
   &lt;dbl&gt;
1 0.0642
2 0.0588
3 0.0961</code></pre>
</div>
</div>
<p>Or we can also predict with confidence interval:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>conf_int_pred <span class="ot">=</span> <span class="fu">predict</span>(lm_fit, <span class="at">new_data =</span> new_obs,</span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>        <span class="at">type =</span> <span class="st">"conf_int"</span>)</span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-4"><a href="#cb50-4" aria-hidden="true" tabindex="-1"></a>conf_int_pred</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 2
  .pred_lower .pred_upper
        &lt;dbl&gt;       &lt;dbl&gt;
1      0.0555      0.0729
2      0.0499      0.0678
3      0.0870      0.105 </code></pre>
</div>
</div>
<p>Let’s combine both predictions and visualise:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>plot_data <span class="ot">&lt;-</span> </span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a>  new_obs <span class="sc">|&gt;</span> </span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">bind_cols</span>(mean_pred) <span class="sc">|&gt;</span> </span>
<span id="cb52-4"><a href="#cb52-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">bind_cols</span>(conf_int_pred)</span>
<span id="cb52-5"><a href="#cb52-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-6"><a href="#cb52-6" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(plot_data, <span class="fu">aes</span>(<span class="at">x =</span> food_regime)) <span class="sc">+</span> </span>
<span id="cb52-7"><a href="#cb52-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">y =</span> .pred)) <span class="sc">+</span> </span>
<span id="cb52-8"><a href="#cb52-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_errorbar</span>(<span class="fu">aes</span>(<span class="at">ymin =</span> .pred_lower, </span>
<span id="cb52-9"><a href="#cb52-9" aria-hidden="true" tabindex="-1"></a>                    <span class="at">ymax =</span> .pred_upper),</span>
<span id="cb52-10"><a href="#cb52-10" aria-hidden="true" tabindex="-1"></a>                <span class="at">width =</span> .<span class="dv">2</span>) <span class="sc">+</span> </span>
<span id="cb52-11"><a href="#cb52-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">y =</span> <span class="st">"urchin size"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="block-II-unit-1_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Another way of building model is using Bayesian approach. In Bayesian approach, the prior distribution is used to build model. Here we need to first declare prior probabilities first and then, we do model building using different engine.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="co"># set the prior distribution</span></span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a>prior_dist <span class="ot">&lt;-</span> rstanarm<span class="sc">::</span><span class="fu">student_t</span>(<span class="at">df =</span> <span class="dv">1</span>)   <span class="co"># Setting up prior probability using t distribution</span></span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-4"><a href="#cb53-4" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb53-5"><a href="#cb53-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-6"><a href="#cb53-6" aria-hidden="true" tabindex="-1"></a><span class="co"># make the parsnip model</span></span>
<span id="cb53-7"><a href="#cb53-7" aria-hidden="true" tabindex="-1"></a>bayes_mod <span class="ot">&lt;-</span>   </span>
<span id="cb53-8"><a href="#cb53-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">linear_reg</span>() <span class="sc">|&gt;</span> </span>
<span id="cb53-9"><a href="#cb53-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set_engine</span>(<span class="st">"stan"</span>,                          <span class="co"># Engine for Bayesian model</span></span>
<span id="cb53-10"><a href="#cb53-10" aria-hidden="true" tabindex="-1"></a>             <span class="at">prior_intercept =</span> prior_dist,</span>
<span id="cb53-11"><a href="#cb53-11" aria-hidden="true" tabindex="-1"></a>             <span class="at">prior =</span> prior_dist,</span>
<span id="cb53-12"><a href="#cb53-12" aria-hidden="true" tabindex="-1"></a>             <span class="at">refresh =</span> <span class="dv">0</span>)</span>
<span id="cb53-13"><a href="#cb53-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-14"><a href="#cb53-14" aria-hidden="true" tabindex="-1"></a><span class="co"># train the model</span></span>
<span id="cb53-15"><a href="#cb53-15" aria-hidden="true" tabindex="-1"></a>bayes_fit <span class="ot">&lt;-</span> </span>
<span id="cb53-16"><a href="#cb53-16" aria-hidden="true" tabindex="-1"></a>  bayes_mod <span class="sc">|&gt;</span> </span>
<span id="cb53-17"><a href="#cb53-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">fit</span>(width <span class="sc">~</span> initial_volume <span class="sc">*</span> food_regime, <span class="at">data =</span> urchins)</span>
<span id="cb53-18"><a href="#cb53-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-19"><a href="#cb53-19" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(bayes_fit, <span class="at">digits =</span> <span class="dv">5</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>parsnip model object

stan_glm
 family:       gaussian [identity]
 formula:      width ~ initial_volume * food_regime
 observations: 72
 predictors:   6
------
                               Median   MAD_SD  
(Intercept)                     0.03305  0.00983
initial_volume                  0.00155  0.00040
food_regimeLow                  0.02026  0.01327
food_regimeHigh                 0.02111  0.01467
initial_volume:food_regimeLow  -0.00128  0.00051
initial_volume:food_regimeHigh  0.00053  0.00071

Auxiliary parameter(s):
      Median  MAD_SD 
sigma 0.02134 0.00190

------
* For help interpreting the printed output see ?print.stanreg
* For info on the priors used see ?prior_summary.stanreg</code></pre>
</div>
</div>
<p>Let’s visualize the Bayesian model:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a>bayes_plot_data <span class="ot">&lt;-</span> </span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a>  new_obs <span class="sc">|&gt;</span> </span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">bind_cols</span>(<span class="fu">predict</span>(bayes_fit, <span class="at">new_data =</span> new_obs)) <span class="sc">|&gt;</span> </span>
<span id="cb55-4"><a href="#cb55-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">bind_cols</span>(<span class="fu">predict</span>(bayes_fit, <span class="at">new_data =</span> new_obs, <span class="at">type =</span> <span class="st">"conf_int"</span>))</span>
<span id="cb55-5"><a href="#cb55-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-6"><a href="#cb55-6" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(bayes_plot_data, <span class="fu">aes</span>(<span class="at">x =</span> food_regime)) <span class="sc">+</span> </span>
<span id="cb55-7"><a href="#cb55-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">y =</span> .pred)) <span class="sc">+</span> </span>
<span id="cb55-8"><a href="#cb55-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_errorbar</span>(<span class="fu">aes</span>(<span class="at">ymin =</span> .pred_lower, <span class="at">ymax =</span> .pred_upper), <span class="at">width =</span> .<span class="dv">2</span>) <span class="sc">+</span> </span>
<span id="cb55-9"><a href="#cb55-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">y =</span> <span class="st">"urchin size"</span>) <span class="sc">+</span> </span>
<span id="cb55-10"><a href="#cb55-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Bayesian model with t(1) prior distribution"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="block-II-unit-1_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="data-pre-processing" class="level2" data-number="6.4">
<h2 data-number="6.4" class="anchored" data-anchor-id="data-pre-processing"><span class="header-section-number">6.4</span> Data Pre-Processing</h2>
<p>Data pre-processing is necessary before building model. In Sea urchin case study we have a perfect data set hence we could straight away jump to model building however it is not the case everytime. You will get messy data most of the time. You need to process the messy data into a polished and organized before building any model. Package <code>recipes</code> is the R package we will use to process the data. So, let’s begin.</p>
<p>The package <code>Recipes</code> has inbuilt series of preprocessing steps, such as:</p>
<ul>
<li><p>Converting qualitative predictors to indicator variables (also known as dummy variables),</p></li>
<li><p>Transforming data to be on a different scale (e.g., taking the logarithm of a variable),</p></li>
<li><p>Transforming whole groups of predictors together,</p></li>
<li><p>Extracting key features from raw variables (e.g., getting the day of the week out of a date variable),</p></li>
</ul>
<p>To use code, you will need to install (use <code>install.packages("packagename")</code> command) the following packages: <code>mlbench, themis,here, kableExtra, lubridate, nycflights13, skimr, tidymodels</code>, and <code>timeDate</code>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidymodels)      <span class="co"># for the recipes package, along with the rest of tidymodels</span></span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Helper packages</span></span>
<span id="cb56-4"><a href="#cb56-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(skimr) </span>
<span id="cb56-5"><a href="#cb56-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(mlbench)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'mlbench' was built under R version 4.4.3</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(themis)</span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(stringr)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'stringr' was built under R version 4.4.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'stringr'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:recipes':

    fixed</code></pre>
</div>
</div>
<p>Soybean is the crop majorly grown in Western India and the crop is prone to 16 different types of diseases. We use following dataset to build a classification model to identify the class of disease:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">"Soybean"</span>, <span class="at">package =</span> <span class="st">"mlbench"</span>)</span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-3"><a href="#cb62-3" aria-hidden="true" tabindex="-1"></a>soy <span class="ot">=</span> <span class="fu">as_tibble</span>(Soybean)</span>
<span id="cb62-4"><a href="#cb62-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-5"><a href="#cb62-5" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(soy)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 683
Columns: 36
$ Class           &lt;fct&gt; diaporthe-stem-canker, diaporthe-stem-canker, diaporth…
$ date            &lt;fct&gt; 6, 4, 3, 3, 6, 5, 5, 4, 6, 4, 6, 4, 3, 6, 6, 5, 6, 4, …
$ plant.stand     &lt;ord&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …
$ precip          &lt;ord&gt; 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, …
$ temp            &lt;ord&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 2, 2, 2, 1, …
$ hail            &lt;fct&gt; 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, …
$ crop.hist       &lt;fct&gt; 1, 2, 1, 1, 2, 3, 2, 1, 3, 2, 1, 1, 1, 3, 1, 3, 0, 2, …
$ area.dam        &lt;fct&gt; 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 3, 2, 3, 3, 3, 2, 2, …
$ sever           &lt;fct&gt; 1, 2, 2, 2, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, …
$ seed.tmt        &lt;fct&gt; 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, …
$ germ            &lt;ord&gt; 0, 1, 2, 1, 2, 1, 0, 2, 1, 2, 0, 1, 0, 0, 1, 2, 0, 1, …
$ plant.growth    &lt;fct&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, …
$ leaves          &lt;fct&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, …
$ leaf.halo       &lt;fct&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …
$ leaf.marg       &lt;fct&gt; 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, …
$ leaf.size       &lt;ord&gt; 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, …
$ leaf.shread     &lt;fct&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …
$ leaf.malf       &lt;fct&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …
$ leaf.mild       &lt;fct&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …
$ stem            &lt;fct&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, …
$ lodging         &lt;fct&gt; 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, …
$ stem.cankers    &lt;fct&gt; 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 0, 0, 0, 0, 0, 0, 0, 0, …
$ canker.lesion   &lt;fct&gt; 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 3, 3, 3, 3, 3, 3, 3, 3, …
$ fruiting.bodies &lt;fct&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, …
$ ext.decay       &lt;fct&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, …
$ mycelium        &lt;fct&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …
$ int.discolor    &lt;fct&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2, …
$ sclerotia       &lt;fct&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, …
$ fruit.pods      &lt;fct&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …
$ fruit.spots     &lt;fct&gt; 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, …
$ seed            &lt;fct&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …
$ mold.growth     &lt;fct&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …
$ seed.discolor   &lt;fct&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …
$ seed.size       &lt;fct&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …
$ shriveling      &lt;fct&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …
$ roots           &lt;fct&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …</code></pre>
</div>
</div>
<p>In the dataset, we have 683 rows and 36 variables. Let’s look at the missingness in the data:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Quick look at missingness and class balance</span></span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a><span class="fu">colSums</span>(<span class="fu">is.na</span>(soy)) <span class="sc">|&gt;</span> </span>
<span id="cb64-3"><a href="#cb64-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">sort</span>(<span class="at">decreasing =</span> <span class="cn">TRUE</span>) <span class="sc">|&gt;</span> </span>
<span id="cb64-4"><a href="#cb64-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>(<span class="dv">10</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>           hail           sever        seed.tmt         lodging            germ 
            121             121             121             121             112 
      leaf.mild fruiting.bodies     fruit.spots   seed.discolor      shriveling 
            108             106             106             106             106 </code></pre>
</div>
</div>
<p>Let’s also check class imbalance in the <code>Class</code> variable that is decision variable (<code>y</code>):</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a>soy <span class="sc">|&gt;</span> </span>
<span id="cb66-2"><a href="#cb66-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(Class, <span class="at">sort =</span> <span class="cn">TRUE</span>) <span class="sc">|&gt;</span> </span>
<span id="cb66-3"><a href="#cb66-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>(<span class="at">n =</span> <span class="dv">20</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 19 × 2
   Class                           n
   &lt;fct&gt;                       &lt;int&gt;
 1 brown-spot                     92
 2 alternarialeaf-spot            91
 3 frog-eye-leaf-spot             91
 4 phytophthora-rot               88
 5 anthracnose                    44
 6 brown-stem-rot                 44
 7 bacterial-blight               20
 8 bacterial-pustule              20
 9 charcoal-rot                   20
10 diaporthe-stem-canker          20
11 downy-mildew                   20
12 phyllosticta-leaf-spot         20
13 powdery-mildew                 20
14 purple-seed-stain              20
15 rhizoctonia-root-rot           20
16 2-4-d-injury                   16
17 diaporthe-pod-&amp;-stem-blight    15
18 cyst-nematode                  14
19 herbicide-injury                8</code></pre>
</div>
</div>
<p>We can clearly see class imbalance here. The disease class <code>herbicide-injury</code> has only 8 observations and disease class <code>brown-spot</code> has 92 observations. When we build model on such imbalanced data, the model will get more discriminant features from higher frequency class and very less discriminant features from the low freqquency class. Consequenly, model will be biased towards higher frequency class which will create a model that can not be reliable.</p>
<p>To sort out this, we need to balance the class frequencies to the equal proportions in the data. But, first we build a classification model with all data preprocessing needed:</p>
<section id="data-split" class="level3" data-number="6.4.1">
<h3 data-number="6.4.1" class="anchored" data-anchor-id="data-split"><span class="header-section-number">6.4.1</span> Data Split</h3>
<p>We train the model on 80% of the data and keep 20% data to test the model. The data is split through stratified random sampling:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">42</span>)</span>
<span id="cb68-2"><a href="#cb68-2" aria-hidden="true" tabindex="-1"></a>split      <span class="ot">&lt;-</span> <span class="fu">initial_split</span>(soy, <span class="at">prop =</span> <span class="fl">0.8</span>, <span class="at">strata =</span> Class)</span>
<span id="cb68-3"><a href="#cb68-3" aria-hidden="true" tabindex="-1"></a>soy_train  <span class="ot">&lt;-</span> <span class="fu">training</span>(split)</span>
<span id="cb68-4"><a href="#cb68-4" aria-hidden="true" tabindex="-1"></a>soy_test   <span class="ot">&lt;-</span> <span class="fu">testing</span>(split)</span>
<span id="cb68-5"><a href="#cb68-5" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb68-6"><a href="#cb68-6" aria-hidden="true" tabindex="-1"></a>soy_train</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 545 × 36
   Class  date  plant.stand precip temp  hail  crop.hist area.dam sever seed.tmt
   &lt;fct&gt;  &lt;fct&gt; &lt;ord&gt;       &lt;ord&gt;  &lt;ord&gt; &lt;fct&gt; &lt;fct&gt;     &lt;fct&gt;    &lt;fct&gt; &lt;fct&gt;   
 1 diapo… 6     0           2      1     0     1         1        1     0       
 2 diapo… 4     0           2      1     0     2         0        2     1       
 3 diapo… 3     0           2      1     0     1         0        2     1       
 4 diapo… 6     0           2      1     0     3         0        1     1       
 5 charc… 6     0           0      2     0     1         3        1     1       
 6 charc… 5     0           0      2     1     3         3        1     1       
 7 rhizo… 0     1           2      0     0     0         1        1     1       
 8 rhizo… 1     1           2      0     0     0         1        1     0       
 9 rhizo… 1     1           2      0     0     1         1        2     0       
10 rhizo… 2     1           2      0     0     1         1        2     0       
# ℹ 535 more rows
# ℹ 26 more variables: germ &lt;ord&gt;, plant.growth &lt;fct&gt;, leaves &lt;fct&gt;,
#   leaf.halo &lt;fct&gt;, leaf.marg &lt;fct&gt;, leaf.size &lt;ord&gt;, leaf.shread &lt;fct&gt;,
#   leaf.malf &lt;fct&gt;, leaf.mild &lt;fct&gt;, stem &lt;fct&gt;, lodging &lt;fct&gt;,
#   stem.cankers &lt;fct&gt;, canker.lesion &lt;fct&gt;, fruiting.bodies &lt;fct&gt;,
#   ext.decay &lt;fct&gt;, mycelium &lt;fct&gt;, int.discolor &lt;fct&gt;, sclerotia &lt;fct&gt;,
#   fruit.pods &lt;fct&gt;, fruit.spots &lt;fct&gt;, seed &lt;fct&gt;, mold.growth &lt;fct&gt;, …</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a>soy_test</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 138 × 36
   Class  date  plant.stand precip temp  hail  crop.hist area.dam sever seed.tmt
   &lt;fct&gt;  &lt;fct&gt; &lt;ord&gt;       &lt;ord&gt;  &lt;ord&gt; &lt;fct&gt; &lt;fct&gt;     &lt;fct&gt;    &lt;fct&gt; &lt;fct&gt;   
 1 diapo… 3     0           2      1     0     1         0        2     0       
 2 charc… 3     0           0      1     0     1         2        1     0       
 3 charc… 4     0           0      1     0     2         2        1     0       
 4 rhizo… 3     0           2      0     1     3         1        2     0       
 5 rhizo… 0     1           2      0     0     1         1        2     1       
 6 rhizo… 2     1           2      0     0     2         1        1     0       
 7 phyto… 0     1           1      1     0     1         1        1     0       
 8 phyto… 2     1           1      1     &lt;NA&gt;  0         1        &lt;NA&gt;  &lt;NA&gt;    
 9 phyto… 2     1           2      0     0     1         1        2     0       
10 phyto… 1     1           2      1     1     3         1        2     0       
# ℹ 128 more rows
# ℹ 26 more variables: germ &lt;ord&gt;, plant.growth &lt;fct&gt;, leaves &lt;fct&gt;,
#   leaf.halo &lt;fct&gt;, leaf.marg &lt;fct&gt;, leaf.size &lt;ord&gt;, leaf.shread &lt;fct&gt;,
#   leaf.malf &lt;fct&gt;, leaf.mild &lt;fct&gt;, stem &lt;fct&gt;, lodging &lt;fct&gt;,
#   stem.cankers &lt;fct&gt;, canker.lesion &lt;fct&gt;, fruiting.bodies &lt;fct&gt;,
#   ext.decay &lt;fct&gt;, mycelium &lt;fct&gt;, int.discolor &lt;fct&gt;, sclerotia &lt;fct&gt;,
#   fruit.pods &lt;fct&gt;, fruit.spots &lt;fct&gt;, seed &lt;fct&gt;, mold.growth &lt;fct&gt;, …</code></pre>
</div>
</div>
<p>You can see that out of 683 observations, soy_train dataset contains 80% observations i.e.&nbsp;545 observations and soy_test dataset contains 20% observations i.e.&nbsp;138 observations.</p>
</section>
<section id="build-the-preprocessing-recipe" class="level3" data-number="6.4.2">
<h3 data-number="6.4.2" class="anchored" data-anchor-id="build-the-preprocessing-recipe"><span class="header-section-number">6.4.2</span> Build the preprocessing <code>recipe</code></h3>
<p>This is the core of the exercise: every cleaning/encoding Decision is captured as a <em>recipe step</em>, learned only on the training set, then reproducibly applied to any new data.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a>soy_recipe <span class="ot">&lt;-</span></span>
<span id="cb72-2"><a href="#cb72-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">recipe</span>(Class <span class="sc">~</span> ., <span class="at">data =</span> soy_train) <span class="sc">|&gt;</span></span>
<span id="cb72-3"><a href="#cb72-3" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb72-4"><a href="#cb72-4" aria-hidden="true" tabindex="-1"></a>  <span class="co"># (a) Drop predictors that are (near) constant -&gt; add no signal</span></span>
<span id="cb72-5"><a href="#cb72-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">step_nzv</span>(<span class="fu">all_predictors</span>()) <span class="sc">|&gt;</span></span>
<span id="cb72-6"><a href="#cb72-6" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb72-7"><a href="#cb72-7" aria-hidden="true" tabindex="-1"></a>  <span class="co"># (b) Handle missing values in categorical predictors</span></span>
<span id="cb72-8"><a href="#cb72-8" aria-hidden="true" tabindex="-1"></a>  <span class="co">#     Bagged trees impute using the other predictors' patterns,</span></span>
<span id="cb72-9"><a href="#cb72-9" aria-hidden="true" tabindex="-1"></a>  <span class="co">#     which works well for structured agronomic survey data.</span></span>
<span id="cb72-10"><a href="#cb72-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">step_impute_bag</span>(<span class="fu">all_nominal_predictors</span>(), <span class="at">impute_with =</span> <span class="fu">imp_vars</span>(<span class="fu">all_predictors</span>())) <span class="sc">|&gt;</span></span>
<span id="cb72-11"><a href="#cb72-11" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb72-12"><a href="#cb72-12" aria-hidden="true" tabindex="-1"></a>  <span class="co"># (c) Collapse rarely-occurring factor levels into "other"</span></span>
<span id="cb72-13"><a href="#cb72-13" aria-hidden="true" tabindex="-1"></a>  <span class="co">#     (prevents unstable dummy columns from very rare categories)</span></span>
<span id="cb72-14"><a href="#cb72-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">step_other</span>(<span class="fu">all_nominal_predictors</span>(), <span class="at">threshold =</span> <span class="fl">0.03</span>, <span class="at">other =</span> <span class="st">"other_level"</span>) <span class="sc">|&gt;</span></span>
<span id="cb72-15"><a href="#cb72-15" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb72-16"><a href="#cb72-16" aria-hidden="true" tabindex="-1"></a>  <span class="co"># (d) Ensure factor levels seen in test/new data don't break the model</span></span>
<span id="cb72-17"><a href="#cb72-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">step_novel</span>(<span class="fu">all_nominal_predictors</span>()) <span class="sc">|&gt;</span></span>
<span id="cb72-18"><a href="#cb72-18" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb72-19"><a href="#cb72-19" aria-hidden="true" tabindex="-1"></a>  <span class="co"># (e) One-hot / dummy encode categorical predictors for models</span></span>
<span id="cb72-20"><a href="#cb72-20" aria-hidden="true" tabindex="-1"></a>  <span class="co">#     that need numeric input</span></span>
<span id="cb72-21"><a href="#cb72-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">step_dummy</span>(<span class="fu">all_nominal_predictors</span>(), <span class="at">one_hot =</span> <span class="cn">TRUE</span>) <span class="sc">|&gt;</span></span>
<span id="cb72-22"><a href="#cb72-22" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb72-23"><a href="#cb72-23" aria-hidden="true" tabindex="-1"></a>  <span class="co"># (f) Remove any dummy columns that are (still) near-zero variance</span></span>
<span id="cb72-24"><a href="#cb72-24" aria-hidden="true" tabindex="-1"></a>  <span class="co">#     after encoding</span></span>
<span id="cb72-25"><a href="#cb72-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">step_nzv</span>(<span class="fu">all_predictors</span>()) <span class="sc">|&gt;</span></span>
<span id="cb72-26"><a href="#cb72-26" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb72-27"><a href="#cb72-27" aria-hidden="true" tabindex="-1"></a>  <span class="co"># (g) Remove highly correlated dummy columns (redundant info)</span></span>
<span id="cb72-28"><a href="#cb72-28" aria-hidden="true" tabindex="-1"></a>  <span class="fu">step_corr</span>(<span class="fu">all_numeric_predictors</span>(), <span class="at">threshold =</span> <span class="fl">0.9</span>) <span class="sc">|&gt;</span></span>
<span id="cb72-29"><a href="#cb72-29" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb72-30"><a href="#cb72-30" aria-hidden="true" tabindex="-1"></a>  <span class="co"># (h) Scale numeric predictors (harmless here, essential if you</span></span>
<span id="cb72-31"><a href="#cb72-31" aria-hidden="true" tabindex="-1"></a>  <span class="co">#     later add real-valued agronomic measurements e.g. rainfall_mm)</span></span>
<span id="cb72-32"><a href="#cb72-32" aria-hidden="true" tabindex="-1"></a>  <span class="fu">step_normalize</span>(<span class="fu">all_numeric_predictors</span>()) <span class="sc">|&gt;</span></span>
<span id="cb72-33"><a href="#cb72-33" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb72-34"><a href="#cb72-34" aria-hidden="true" tabindex="-1"></a>  <span class="co"># (i) Address class imbalance (19 disease classes, some very rare)</span></span>
<span id="cb72-35"><a href="#cb72-35" aria-hidden="true" tabindex="-1"></a>  <span class="co">#     using up-sampling on the TRAINING data only</span></span>
<span id="cb72-36"><a href="#cb72-36" aria-hidden="true" tabindex="-1"></a>  <span class="fu">step_upsample</span>(Class, <span class="at">over_ratio =</span> <span class="fl">0.5</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="inspect-the-recipe-without-training-a-model" class="level3" data-number="6.4.3">
<h3 data-number="6.4.3" class="anchored" data-anchor-id="inspect-the-recipe-without-training-a-model"><span class="header-section-number">6.4.3</span> Inspect the recipe without training a model</h3>
<p><code>prep()</code> estimates all step parameters (imputation models, which levels to pool, correlation matrix, normalization mean/sd, etc.) using soy_train ONLY - no leakage from soy_test.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a>soy_prep <span class="ot">&lt;-</span> <span class="fu">prep</span>(soy_recipe, <span class="at">training =</span> soy_train)</span>
<span id="cb73-2"><a href="#cb73-2" aria-hidden="true" tabindex="-1"></a>soy_prep</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code></code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>── Recipe ──────────────────────────────────────────────────────────────────────</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code></code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>── Inputs </code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Number of variables by role</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>outcome:    1
predictor: 35</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code></code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>── Training information </code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Training data contained 545 data points and 95 incomplete rows.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code></code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>── Operations </code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>• Sparse, unbalanced variable filter removed: leaf.mild, ... | Trained</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>• Bagged tree imputation for: date, plant.stand, precip, temp, ... | Trained</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>• Collapsing factor levels for: leaf.marg ext.decay, ... | Trained</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>• Novel factor level assignment for: date plant.stand, ... | Trained</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>• Dummy variables from: date, plant.stand, precip, temp, hail, ... | Trained</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>• Sparse, unbalanced variable filter removed: date_X0, ... | Trained</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>• Correlation filter on: seed.tmt_X1 leaf.marg_X0, ... | Trained</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>• Centering and scaling for: date_X1, date_X2, date_X3, ... | Trained</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>• Up-sampling based on: Class | Trained</code></pre>
</div>
</div>
</section>
<section id="data-pransformation-for-model" class="level3" data-number="6.4.4">
<h3 data-number="6.4.4" class="anchored" data-anchor-id="data-pransformation-for-model"><span class="header-section-number">6.4.4</span> Data Pransformation for Model</h3>
<p><code>bake()</code> applies the learned transformations to produce the final model-ready data frame:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb94"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb94-1"><a href="#cb94-1" aria-hidden="true" tabindex="-1"></a>train_baked <span class="ot">&lt;-</span> <span class="fu">bake</span>(soy_prep, <span class="at">new_data =</span> <span class="cn">NULL</span>)   <span class="co"># transformed training data</span></span>
<span id="cb94-2"><a href="#cb94-2" aria-hidden="true" tabindex="-1"></a>test_baked  <span class="ot">&lt;-</span> <span class="fu">bake</span>(soy_prep, <span class="at">new_data =</span> soy_test)  <span class="co"># test data, same transforms</span></span>
<span id="cb94-3"><a href="#cb94-3" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb94-4"><a href="#cb94-4" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(train_baked)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 848  64</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb96"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb96-1"><a href="#cb96-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(test_baked)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 138  64</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb98"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb98-1"><a href="#cb98-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">is.na</span>(train_baked))   <span class="co"># should be 0 - imputation worked</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0</code></pre>
</div>
</div>
</section>
<section id="plug-the-recipe-into-a-modeling-workflow" class="level3" data-number="6.4.5">
<h3 data-number="6.4.5" class="anchored" data-anchor-id="plug-the-recipe-into-a-modeling-workflow"><span class="header-section-number">6.4.5</span> Plug the recipe into a modeling workflow</h3>
<p>We use random forest algorithm to build the model.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb100"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb100-1"><a href="#cb100-1" aria-hidden="true" tabindex="-1"></a>rf_spec <span class="ot">&lt;-</span> <span class="fu">rand_forest</span>(<span class="at">trees =</span> <span class="dv">500</span>) <span class="sc">|&gt;</span></span>
<span id="cb100-2"><a href="#cb100-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set_engine</span>(<span class="st">"ranger"</span>) <span class="sc">|&gt;</span></span>
<span id="cb100-3"><a href="#cb100-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set_mode</span>(<span class="st">"classification"</span>)</span>
<span id="cb100-4"><a href="#cb100-4" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb100-5"><a href="#cb100-5" aria-hidden="true" tabindex="-1"></a>soy_workflow <span class="ot">&lt;-</span> <span class="fu">workflow</span>() <span class="sc">|&gt;</span></span>
<span id="cb100-6"><a href="#cb100-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_recipe</span>(soy_recipe) <span class="sc">|&gt;</span></span>
<span id="cb100-7"><a href="#cb100-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_model</span>(rf_spec)</span>
<span id="cb100-8"><a href="#cb100-8" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb100-9"><a href="#cb100-9" aria-hidden="true" tabindex="-1"></a>soy_fit <span class="ot">&lt;-</span> <span class="fu">fit</span>(soy_workflow, <span class="at">data =</span> soy_train)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="evaluate-on-held-out-test-data" class="level3" data-number="6.4.6">
<h3 data-number="6.4.6" class="anchored" data-anchor-id="evaluate-on-held-out-test-data"><span class="header-section-number">6.4.6</span> Evaluate on held-out test data</h3>
<p>In the previous step, we have built a machine learning model named as <code>soy_fit</code> and to test the accuracy of the model, we use test data and create prediction of the diseases based on the predictors:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb101"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb101-1"><a href="#cb101-1" aria-hidden="true" tabindex="-1"></a>soy_preds <span class="ot">&lt;-</span> <span class="fu">predict</span>(soy_fit, <span class="at">new_data =</span> soy_test) <span class="sc">|&gt;</span></span>
<span id="cb101-2"><a href="#cb101-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">bind_cols</span>(soy_test <span class="sc">|&gt;</span> <span class="fu">select</span>(Class))</span>
<span id="cb101-3"><a href="#cb101-3" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb101-4"><a href="#cb101-4" aria-hidden="true" tabindex="-1"></a><span class="fu">accuracy</span>(soy_preds, <span class="at">truth =</span> Class, <span class="at">estimate =</span> .pred_class)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 3
  .metric  .estimator .estimate
  &lt;chr&gt;    &lt;chr&gt;          &lt;dbl&gt;
1 accuracy multiclass     0.928</code></pre>
</div>
</div>
<p>We can see that the accuracy of the model is 92.8% which means out of 100 attempts of classification, model is able to predict accurately is 92.8%.</p>
<p>Let’s deep dive into classification accuracy using confusion matrix:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb103"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb103-1"><a href="#cb103-1" aria-hidden="true" tabindex="-1"></a>soy_preds <span class="sc">|&gt;</span> <span class="fu">conf_mat</span>(<span class="at">truth =</span> Class, <span class="at">estimate =</span> .pred_class) <span class="sc">|&gt;</span></span>
<span id="cb103-2"><a href="#cb103-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summary</span>() <span class="sc">|&gt;</span></span>
<span id="cb103-3"><a href="#cb103-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(.metric <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"accuracy"</span>, <span class="st">"kap"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 3
  .metric  .estimator .estimate
  &lt;chr&gt;    &lt;chr&gt;          &lt;dbl&gt;
1 accuracy multiclass     0.928
2 kap      multiclass     0.921</code></pre>
</div>
</div>
<p>Let’s evaluate model accuracy for each class of disease in soybean:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb105"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb105-1"><a href="#cb105-1" aria-hidden="true" tabindex="-1"></a>soy_probs <span class="ot">&lt;-</span> <span class="fu">predict</span>(soy_fit, <span class="at">new_data =</span> soy_test, <span class="at">type =</span> <span class="st">"prob"</span>) <span class="sc">|&gt;</span></span>
<span id="cb105-2"><a href="#cb105-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">bind_cols</span>(soy_test <span class="sc">|&gt;</span> <span class="fu">select</span>(Class))</span>
<span id="cb105-3"><a href="#cb105-3" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb105-4"><a href="#cb105-4" aria-hidden="true" tabindex="-1"></a>soy_probs <span class="sc">|&gt;</span> <span class="fu">head</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 20
  `.pred_2-4-d-injury` `.pred_alternarialeaf-spot` .pred_anthracnose
                 &lt;dbl&gt;                       &lt;dbl&gt;             &lt;dbl&gt;
1             0.000211                           0           0.00344
2             0.002                              0           0.002  
3             0.002                              0           0.00222
4             0.000413                           0           0.0065 
5             0.000413                           0           0      
6             0.000413                           0           0.00183
# ℹ 17 more variables: `.pred_bacterial-blight` &lt;dbl&gt;,
#   `.pred_bacterial-pustule` &lt;dbl&gt;, `.pred_brown-spot` &lt;dbl&gt;,
#   `.pred_brown-stem-rot` &lt;dbl&gt;, `.pred_charcoal-rot` &lt;dbl&gt;,
#   `.pred_cyst-nematode` &lt;dbl&gt;, `.pred_diaporthe-pod-&amp;-stem-blight` &lt;dbl&gt;,
#   `.pred_diaporthe-stem-canker` &lt;dbl&gt;, `.pred_downy-mildew` &lt;dbl&gt;,
#   `.pred_frog-eye-leaf-spot` &lt;dbl&gt;, `.pred_herbicide-injury` &lt;dbl&gt;,
#   `.pred_phyllosticta-leaf-spot` &lt;dbl&gt;, `.pred_phytophthora-rot` &lt;dbl&gt;, …</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb107"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb107-1"><a href="#cb107-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Columns look like: .pred_brown-spot, .pred_frog-eye-leaf-spot, ... , Class</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="multiclass-roc-one-vs-rest" class="level3" data-number="6.4.7">
<h3 data-number="6.4.7" class="anchored" data-anchor-id="multiclass-roc-one-vs-rest"><span class="header-section-number">6.4.7</span> Multiclass ROC (one-vs-rest)</h3>
<p>The <code>roc_curve()</code> automatically does one-vs-rest for a multi-level truth column when you pass all the .pred_* probability columns.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb108"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb108-1"><a href="#cb108-1" aria-hidden="true" tabindex="-1"></a>prob_cols <span class="ot">&lt;-</span> <span class="fu">names</span>(soy_probs) <span class="sc">|&gt;</span> <span class="fu">str_subset</span>(<span class="st">"^</span><span class="sc">\\</span><span class="st">.pred_"</span>)</span>
<span id="cb108-2"><a href="#cb108-2" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb108-3"><a href="#cb108-3" aria-hidden="true" tabindex="-1"></a>roc_data <span class="ot">&lt;-</span> <span class="fu">roc_curve</span>(</span>
<span id="cb108-4"><a href="#cb108-4" aria-hidden="true" tabindex="-1"></a>  soy_probs,</span>
<span id="cb108-5"><a href="#cb108-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">truth =</span> Class,</span>
<span id="cb108-6"><a href="#cb108-6" aria-hidden="true" tabindex="-1"></a>  <span class="sc">!!!</span><span class="fu">syms</span>(prob_cols)</span>
<span id="cb108-7"><a href="#cb108-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb108-8"><a href="#cb108-8" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb108-9"><a href="#cb108-9" aria-hidden="true" tabindex="-1"></a><span class="do">## Per-class AUC (one-vs-rest)</span></span>
<span id="cb108-10"><a href="#cb108-10" aria-hidden="true" tabindex="-1"></a><span class="do">## a multiclass setting we loop over each class, re-code it as a</span></span>
<span id="cb108-11"><a href="#cb108-11" aria-hidden="true" tabindex="-1"></a><span class="do">## binary "this class vs. all others" problem, and score that.</span></span>
<span id="cb108-12"><a href="#cb108-12" aria-hidden="true" tabindex="-1"></a>class_levels <span class="ot">&lt;-</span> <span class="fu">levels</span>(soy_probs<span class="sc">$</span>Class)</span>
<span id="cb108-13"><a href="#cb108-13" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb108-14"><a href="#cb108-14" aria-hidden="true" tabindex="-1"></a>roc_auc_by_class <span class="ot">&lt;-</span> <span class="fu">map_dfr</span>(class_levels, <span class="cf">function</span>(cls) {</span>
<span id="cb108-15"><a href="#cb108-15" aria-hidden="true" tabindex="-1"></a>  prob_col <span class="ot">&lt;-</span> <span class="fu">paste0</span>(<span class="st">".pred_"</span>, cls)</span>
<span id="cb108-16"><a href="#cb108-16" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb108-17"><a href="#cb108-17" aria-hidden="true" tabindex="-1"></a>  binary_truth <span class="ot">&lt;-</span> <span class="fu">factor</span>(</span>
<span id="cb108-18"><a href="#cb108-18" aria-hidden="true" tabindex="-1"></a>    <span class="fu">if_else</span>(soy_probs<span class="sc">$</span>Class <span class="sc">==</span> cls, cls, <span class="st">"other"</span>),</span>
<span id="cb108-19"><a href="#cb108-19" aria-hidden="true" tabindex="-1"></a>    <span class="at">levels =</span> <span class="fu">c</span>(cls, <span class="st">"other"</span>)   <span class="co"># cls = "event" / first level</span></span>
<span id="cb108-20"><a href="#cb108-20" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb108-21"><a href="#cb108-21" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb108-22"><a href="#cb108-22" aria-hidden="true" tabindex="-1"></a>  bin_auc <span class="ot">&lt;-</span> <span class="fu">roc_auc</span>(</span>
<span id="cb108-23"><a href="#cb108-23" aria-hidden="true" tabindex="-1"></a>    <span class="fu">tibble</span>(<span class="at">truth =</span> binary_truth, <span class="at">prob =</span> soy_probs[[prob_col]]),</span>
<span id="cb108-24"><a href="#cb108-24" aria-hidden="true" tabindex="-1"></a>    <span class="at">truth =</span> truth,</span>
<span id="cb108-25"><a href="#cb108-25" aria-hidden="true" tabindex="-1"></a>    prob,</span>
<span id="cb108-26"><a href="#cb108-26" aria-hidden="true" tabindex="-1"></a>    <span class="at">event_level =</span> <span class="st">"first"</span></span>
<span id="cb108-27"><a href="#cb108-27" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb108-28"><a href="#cb108-28" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb108-29"><a href="#cb108-29" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tibble</span>(<span class="at">.level =</span> cls, <span class="at">.estimate =</span> bin_auc<span class="sc">$</span>.estimate)</span>
<span id="cb108-30"><a href="#cb108-30" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb108-31"><a href="#cb108-31" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb108-32"><a href="#cb108-32" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(roc_auc_by_class, <span class="at">n =</span> <span class="cn">Inf</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 19 × 2
   .level                      .estimate
   &lt;chr&gt;                           &lt;dbl&gt;
 1 2-4-d-injury                    1    
 2 alternarialeaf-spot             0.992
 3 anthracnose                     1    
 4 bacterial-blight                0.998
 5 bacterial-pustule               0.998
 6 brown-spot                      0.998
 7 brown-stem-rot                  1    
 8 charcoal-rot                    1    
 9 cyst-nematode                   1    
10 diaporthe-pod-&amp;-stem-blight     1    
11 diaporthe-stem-canker           1    
12 downy-mildew                    1    
13 frog-eye-leaf-spot              0.991
14 herbicide-injury                1    
15 phyllosticta-leaf-spot          1    
16 phytophthora-rot                1    
17 powdery-mildew                  1    
18 purple-seed-stain               1    
19 rhizoctonia-root-rot            1    </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb110"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb110-1"><a href="#cb110-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Overall macro-average AUC (what you'd usually report as "the" AUC)</span></span>
<span id="cb110-2"><a href="#cb110-2" aria-hidden="true" tabindex="-1"></a>roc_auc_macro <span class="ot">&lt;-</span> <span class="fu">roc_auc</span>(</span>
<span id="cb110-3"><a href="#cb110-3" aria-hidden="true" tabindex="-1"></a>  soy_probs,</span>
<span id="cb110-4"><a href="#cb110-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">truth =</span> Class,</span>
<span id="cb110-5"><a href="#cb110-5" aria-hidden="true" tabindex="-1"></a>  <span class="sc">!!!</span><span class="fu">syms</span>(prob_cols)</span>
<span id="cb110-6"><a href="#cb110-6" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb110-7"><a href="#cb110-7" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(roc_auc_macro)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 3
  .metric .estimator .estimate
  &lt;chr&gt;   &lt;chr&gt;          &lt;dbl&gt;
1 roc_auc hand_till      0.999</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb112"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb112-1"><a href="#cb112-1" aria-hidden="true" tabindex="-1"></a><span class="do">## ---- 6a. Quick built-in plot: one ROC curve per class, faceted ----</span></span>
<span id="cb112-2"><a href="#cb112-2" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(roc_data) <span class="sc">+</span></span>
<span id="cb112-3"><a href="#cb112-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"One-vs-Rest ROC Curves per Soybean Disease Class"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="block-II-unit-1_files/figure-html/unnamed-chunk-27-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb113"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb113-1"><a href="#cb113-1" aria-hidden="true" tabindex="-1"></a><span class="do">## ---- 6b. All classes overlaid on ONE plot, AUC in the legend ------</span></span>
<span id="cb113-2"><a href="#cb113-2" aria-hidden="true" tabindex="-1"></a>auc_labels <span class="ot">&lt;-</span> roc_auc_by_class <span class="sc">|&gt;</span></span>
<span id="cb113-3"><a href="#cb113-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">label =</span> <span class="fu">paste0</span>(.level, <span class="st">" (AUC = "</span>, <span class="fu">round</span>(.estimate, <span class="dv">2</span>), <span class="st">")"</span>))</span>
<span id="cb113-4"><a href="#cb113-4" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb113-5"><a href="#cb113-5" aria-hidden="true" tabindex="-1"></a>roc_data <span class="sc">|&gt;</span></span>
<span id="cb113-6"><a href="#cb113-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(auc_labels, <span class="at">by =</span> <span class="st">".level"</span>) <span class="sc">|&gt;</span></span>
<span id="cb113-7"><a href="#cb113-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="dv">1</span> <span class="sc">-</span> specificity, <span class="at">y =</span> sensitivity, <span class="at">color =</span> label)) <span class="sc">+</span></span>
<span id="cb113-8"><a href="#cb113-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_path</span>(<span class="at">linewidth =</span> <span class="fl">0.9</span>) <span class="sc">+</span></span>
<span id="cb113-9"><a href="#cb113-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">lty =</span> <span class="dv">3</span>, <span class="at">color =</span> <span class="st">"grey50"</span>) <span class="sc">+</span></span>
<span id="cb113-10"><a href="#cb113-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_equal</span>() <span class="sc">+</span></span>
<span id="cb113-11"><a href="#cb113-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb113-12"><a href="#cb113-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">title    =</span> <span class="st">"Multiclass ROC Curves — Soybean Disease Classification"</span>,</span>
<span id="cb113-13"><a href="#cb113-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="st">"One-vs-rest, colored by disease class"</span>,</span>
<span id="cb113-14"><a href="#cb113-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"1 - Specificity (False Positive Rate)"</span>,</span>
<span id="cb113-15"><a href="#cb113-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Sensitivity (True Positive Rate)"</span>,</span>
<span id="cb113-16"><a href="#cb113-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">"Disease (AUC)"</span></span>
<span id="cb113-17"><a href="#cb113-17" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb113-18"><a href="#cb113-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb113-19"><a href="#cb113-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.text =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">8</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="block-II-unit-1_files/figure-html/unnamed-chunk-27-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Let’s discuss each part of Multi-Class ROC curves:</p>
<ul>
<li><p><span class="math display">\[ Sensitivity (True Positive Rate) = True_Positive_Cases / (True_Positive_Cases + False_Negative_Cases) \]</span></p></li>
<li><p><span class="math display">\[ Specificity (False Positive Rate) = True_Negative_Cases / (True_Negative_Cases + False_Positive_Cases) \]</span></p></li>
</ul>
</section>
<section id="concluding-remarks" class="level3" data-number="6.4.8">
<h3 data-number="6.4.8" class="anchored" data-anchor-id="concluding-remarks"><span class="header-section-number">6.4.8</span> Concluding Remarks</h3>
<p>This analysis demonstrated an end-to-end multiclass classification pipeline for diagnosing soybean diseases from categorical agronomic and environmental observations. The <code>recipes</code> package handled the preprocessing burden reproducibly and without data leakage — filtering near-zero-variance predictors, imputing missing symptom records via bagged trees, pooling rare factor levels, one-hot encoding, removing redundant correlated features, and upsampling rare disease classes — all learned strictly on the training split and applied identically to the held-out test data.</p>
<p>The random forest classifier trained on this preprocessed data was evaluated using one-vs-rest ROC curves for each disease class rather than a single aggregate accuracy figure, since accuracy alone can mask poor performance on rarer or harder-to-distinguish diseases. Per-class AUC values reveal which diseases the model separates cleanly from all others (curves hugging the top-left corner, AUC near 1.0) versus which ones it confuses with visually or symptomatically similar conditions (curves closer to the diagonal, AUC near 0.5). This class-by-class view is more actionable for an agribusiness context than a single overall score — it tells you specifically which diseases a field-deployed diagnostic tool can be trusted on, and which would still need expert/agronomist confirmation before acting on the model’s flag.</p>
<p><strong>Practical takeaway:</strong> the preprocessing recipe is reusable well beyond this dataset — swap in real farm records (soil tests, weather logs, crop-cam imagery-derived features, past yield data) and the same <code>step_impute_*</code> → <code>step_other</code>/<code>step_novel</code> → <code>step_dummy</code> → <code>step_corr</code>/<code>step_nzv</code> → <code>step_normalize</code> → <code>step_upsample</code> sequence provides a robust, leakage-free foundation for any agribusiness classification problem — whether that’s disease diagnosis, loan-default risk for agri-lending, or yield-grade prediction.</p>
<hr>
</section>
</section>
<section id="regression-methods" class="level2" data-number="6.5">
<h2 data-number="6.5" class="anchored" data-anchor-id="regression-methods"><span class="header-section-number">6.5</span> Regression Methods</h2>
<p>Regression methods are used to build model to predict the estimate or classify an obervation. In this section we will cover linear regression, nonlinear regression, multiple regression, polynomial regression,lasso regression, ridge regression, stepwise regression, quantile regression and logistic regression.</p>
<p>All examples use ONE simulated crop-yield dataset so you can compare techniques on the same problem:</p>
<p><strong>Predict crop YIELD (kg/hectare) from rainfall, fertilizer,temperature, and soil pH — plus a binary GOOD_YIELD outcome</strong></p>
<p>So, let’s begin with calling the libraries required:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb114"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb114-1"><a href="#cb114-1" aria-hidden="true" tabindex="-1"></a><span class="co"># install.packages(c("glmnet", "quantreg", "ggplot2"))</span></span>
<span id="cb114-2"><a href="#cb114-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(glmnet)     <span class="co"># ridge &amp; lasso</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'glmnet' was built under R version 4.4.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: Matrix</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'Matrix' was built under R version 4.4.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'Matrix'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:tidyr':

    expand, pack, unpack</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loaded glmnet 4.1-10</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb121"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb121-1"><a href="#cb121-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(quantreg)   <span class="co"># quantile regression</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'quantreg' was built under R version 4.4.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: SparseM</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'SparseM'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:Matrix':

    det</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb126"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb126-1"><a href="#cb126-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)    <span class="co"># plotting</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<section id="simulate-data" class="level3" data-number="6.5.1">
<h3 data-number="6.5.1" class="anchored" data-anchor-id="simulate-data"><span class="header-section-number">6.5.1</span> Simulate Data</h3>
<p>We create a dataset of 200 observations and variables are as follows:</p>
<ul>
<li><code>rainfall_mm</code>: Average rainfall measured in mm using mean 800 and standard deviation 150.</li>
<li><code>fertilizer_kg</code>: Fertilizer consumed in KG using max use 150 Kg and min use 20 Kg.</li>
<li><code>temperature_C</code>: Temperature measured in degree centigrade with mean 27 and standard deviation 3.</li>
<li><code>soil_ph</code>: Soil PH created with mean 6.5 and standard deviation 0.5.</li>
<li><code>yeild_kg_ha</code>: Yeild per Hectare using a regression equation.</li>
</ul>
<p>We create a dataset by combining all the variables and we also add one more factor variable - <code>good_yield</code> using <code>if_else</code> logic.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb127"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb127-1"><a href="#cb127-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb127-2"><a href="#cb127-2" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="dv">200</span></span>
<span id="cb127-3"><a href="#cb127-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb127-4"><a href="#cb127-4" aria-hidden="true" tabindex="-1"></a>rainfall_mm  <span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="fu">rnorm</span>(n, <span class="at">mean =</span> <span class="dv">800</span>, <span class="at">sd =</span> <span class="dv">150</span>), <span class="dv">1</span>)</span>
<span id="cb127-5"><a href="#cb127-5" aria-hidden="true" tabindex="-1"></a>fertilizer_kg<span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="fu">runif</span>(n, <span class="dv">20</span>, <span class="dv">150</span>), <span class="dv">1</span>)</span>
<span id="cb127-6"><a href="#cb127-6" aria-hidden="true" tabindex="-1"></a>temperature_C<span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="fu">rnorm</span>(n, <span class="at">mean =</span> <span class="dv">27</span>, <span class="at">sd =</span> <span class="dv">3</span>), <span class="dv">1</span>)</span>
<span id="cb127-7"><a href="#cb127-7" aria-hidden="true" tabindex="-1"></a>soil_ph      <span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="fu">rnorm</span>(n, <span class="at">mean =</span> <span class="fl">6.5</span>, <span class="at">sd =</span> <span class="fl">0.5</span>), <span class="dv">2</span>)</span>
<span id="cb127-8"><a href="#cb127-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb127-9"><a href="#cb127-9" aria-hidden="true" tabindex="-1"></a><span class="do">## Yield has a linear-ish relationship with rainfall/fertilizer/pH,</span></span>
<span id="cb127-10"><a href="#cb127-10" aria-hidden="true" tabindex="-1"></a><span class="do">## but a NONLINEAR (diminishing-returns) relationship with fertilizer,</span></span>
<span id="cb127-11"><a href="#cb127-11" aria-hidden="true" tabindex="-1"></a><span class="do">## and a curved (polynomial) relationship with temperature (yield</span></span>
<span id="cb127-12"><a href="#cb127-12" aria-hidden="true" tabindex="-1"></a><span class="do">## drops off if it gets too hot or too cold - not just "more is better")</span></span>
<span id="cb127-13"><a href="#cb127-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb127-14"><a href="#cb127-14" aria-hidden="true" tabindex="-1"></a>yield_kg_ha <span class="ot">&lt;-</span> <span class="dv">2000</span> <span class="sc">+</span></span>
<span id="cb127-15"><a href="#cb127-15" aria-hidden="true" tabindex="-1"></a>  <span class="fl">2.5</span>   <span class="sc">*</span> rainfall_mm <span class="sc">+</span></span>
<span id="cb127-16"><a href="#cb127-16" aria-hidden="true" tabindex="-1"></a>  <span class="dv">40</span>    <span class="sc">*</span> <span class="fu">sqrt</span>(fertilizer_kg) <span class="sc">-</span>             <span class="co"># diminishing returns</span></span>
<span id="cb127-17"><a href="#cb127-17" aria-hidden="true" tabindex="-1"></a>  <span class="dv">15</span>    <span class="sc">*</span> (temperature_C <span class="sc">-</span> <span class="dv">27</span>)<span class="sc">^</span><span class="dv">2</span> <span class="sc">+</span>          <span class="co"># optimal temp ~27C</span></span>
<span id="cb127-18"><a href="#cb127-18" aria-hidden="true" tabindex="-1"></a>  <span class="dv">300</span>   <span class="sc">*</span> soil_ph <span class="sc">+</span></span>
<span id="cb127-19"><a href="#cb127-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rnorm</span>(n, <span class="dv">0</span>, <span class="dv">200</span>)</span>
<span id="cb127-20"><a href="#cb127-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb127-21"><a href="#cb127-21" aria-hidden="true" tabindex="-1"></a>crop <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(rainfall_mm, fertilizer_kg, temperature_C, soil_ph, yield_kg_ha)</span>
<span id="cb127-22"><a href="#cb127-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb127-23"><a href="#cb127-23" aria-hidden="true" tabindex="-1"></a><span class="do">## Binary outcome for logistic regression: "good yield" = above median</span></span>
<span id="cb127-24"><a href="#cb127-24" aria-hidden="true" tabindex="-1"></a>crop<span class="sc">$</span>good_yield <span class="ot">&lt;-</span> <span class="fu">factor</span>(<span class="fu">ifelse</span>(crop<span class="sc">$</span>yield_kg_ha <span class="sc">&gt;</span> <span class="fu">median</span>(crop<span class="sc">$</span>yield_kg_ha), <span class="dv">1</span>, <span class="dv">0</span>))</span>
<span id="cb127-25"><a href="#cb127-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb127-26"><a href="#cb127-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb127-27"><a href="#cb127-27" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(crop)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 200
Columns: 6
$ rainfall_mm   &lt;dbl&gt; 715.9, 765.5, 1033.8, 810.6, 819.4, 1057.3, 869.1, 610.2…
$ fertilizer_kg &lt;dbl&gt; 148.2, 37.8, 137.7, 94.9, 71.4, 78.5, 111.8, 30.7, 64.1,…
$ temperature_C &lt;dbl&gt; 24.9, 24.7, 24.2, 23.8, 25.7, 28.0, 21.0, 27.6, 30.7, 33…
$ soil_ph       &lt;dbl&gt; 6.20, 6.00, 7.01, 6.88, 5.75, 6.45, 6.05, 5.46, 6.58, 6.…
$ yield_kg_ha   &lt;dbl&gt; 5924.906, 5572.238, 6900.664, 6350.336, 5813.202, 7035.6…
$ good_yield    &lt;fct&gt; 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0,…</code></pre>
</div>
</div>
</section>
<section id="traintest-split-8020" class="level3" data-number="6.5.2">
<h3 data-number="6.5.2" class="anchored" data-anchor-id="traintest-split-8020"><span class="header-section-number">6.5.2</span> Train/test split (80/20)</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb129"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb129-1"><a href="#cb129-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">42</span>)</span>
<span id="cb129-2"><a href="#cb129-2" aria-hidden="true" tabindex="-1"></a>train_idx <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="fu">seq_len</span>(n), <span class="at">size =</span> <span class="fl">0.8</span> <span class="sc">*</span> n)</span>
<span id="cb129-3"><a href="#cb129-3" aria-hidden="true" tabindex="-1"></a>train <span class="ot">&lt;-</span> crop[train_idx, ]</span>
<span id="cb129-4"><a href="#cb129-4" aria-hidden="true" tabindex="-1"></a>test  <span class="ot">&lt;-</span> crop[<span class="sc">-</span>train_idx, ]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="linear-regression" class="level3" data-number="6.5.3">
<h3 data-number="6.5.3" class="anchored" data-anchor-id="linear-regression"><span class="header-section-number">6.5.3</span> LINEAR REGRESSION</h3>
<p>To understand linear regression, we build mode with One predictor, straight-line relationship: yield vs.&nbsp;rainfall</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb130"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb130-1"><a href="#cb130-1" aria-hidden="true" tabindex="-1"></a>lm_simple <span class="ot">&lt;-</span> <span class="fu">lm</span>(yield_kg_ha <span class="sc">~</span> rainfall_mm, <span class="at">data =</span> train)</span>
<span id="cb130-2"><a href="#cb130-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm_simple)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = yield_kg_ha ~ rainfall_mm, data = train)

Residuals:
     Min       1Q   Median       3Q      Max 
-1138.21  -217.55    69.47   212.02   814.09 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 4299.7736   151.5065   28.38   &lt;2e-16 ***
rainfall_mm    2.3660     0.1882   12.57   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 333.1 on 158 degrees of freedom
Multiple R-squared:  0.5002,    Adjusted R-squared:  0.497 
F-statistic: 158.1 on 1 and 158 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>A simple linear regression was conducted to examine whether rainfall predicted crop yield. The overall model was statistically significant, <em>F</em>(1, 158) = 158.10, <em>p</em> &lt; .001, and explained approximately 50% of the variance in yield, <em>R</em>² = .50, adjusted <em>R</em>² = .497.</p>
<p>Rainfall was a significant positive predictor of yield, <em>b</em> = 2.37, <em>SE</em> = 0.19, <em>t</em>(158) = 12.57, <em>p</em> &lt; .001. For every additional millimeter of rainfall, yield increased by approximately 2.37 kg/hectare, holding all else constant. The intercept, <em>b</em> = 4299.77, <em>SE</em> = 151.51, <em>t</em>(158) = 28.38, <em>p</em> &lt; .001, represents the model’s predicted yield when rainfall is zero, though this value has limited practical interpretation since zero rainfall falls well outside the observed range of the data.</p>
<p>Let’s check the relationship using visualization:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb132"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb132-1"><a href="#cb132-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(train, <span class="fu">aes</span>(rainfall_mm, yield_kg_ha)) <span class="sc">+</span></span>
<span id="cb132-2"><a href="#cb132-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb132-3"><a href="#cb132-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">TRUE</span>, <span class="at">color =</span> <span class="st">"steelblue"</span>) <span class="sc">+</span></span>
<span id="cb132-4"><a href="#cb132-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Linear Regression: Yield vs. Rainfall"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="block-II-unit-1_files/figure-html/unnamed-chunk-32-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="multiple-regression" class="level3" data-number="6.5.4">
<h3 data-number="6.5.4" class="anchored" data-anchor-id="multiple-regression"><span class="header-section-number">6.5.4</span> MULTIPLE REGRESSION</h3>
<p>Now, we build model with Several predictors, each assumed to have a straight-line (additive) effect on yield:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb134"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb134-1"><a href="#cb134-1" aria-hidden="true" tabindex="-1"></a>lm_multiple <span class="ot">&lt;-</span> <span class="fu">lm</span>(yield_kg_ha <span class="sc">~</span> rainfall_mm <span class="sc">+</span> fertilizer_kg <span class="sc">+</span> temperature_C <span class="sc">+</span> soil_ph,</span>
<span id="cb134-2"><a href="#cb134-2" aria-hidden="true" tabindex="-1"></a>                   <span class="at">data =</span> train)</span>
<span id="cb134-3"><a href="#cb134-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm_multiple)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = yield_kg_ha ~ rainfall_mm + fertilizer_kg + temperature_C + 
    soil_ph, data = train)

Residuals:
     Min       1Q   Median       3Q      Max 
-1017.50  -187.31    38.67   186.97   617.16 

Coefficients:
               Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   2319.5617   396.0693   5.856 2.74e-08 ***
rainfall_mm      2.3383     0.1617  14.459  &lt; 2e-16 ***
fertilizer_kg    2.5336     0.5959   4.252 3.65e-05 ***
temperature_C   -0.6421     7.7034  -0.083    0.934    
soil_ph        278.4878    44.6961   6.231 4.19e-09 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 283.5 on 155 degrees of freedom
Multiple R-squared:  0.6447,    Adjusted R-squared:  0.6355 
F-statistic:  70.3 on 4 and 155 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb136"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb136-1"><a href="#cb136-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Compare R-squared to the simple model - more predictors usually</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Two regression models were compared to evaluate the predictors of crop yield. The simple linear regression, using rainfall alone, was statistically significant and explained approximately 50% of the variance in yield, <em>R</em>² = .50, adjusted <em>R</em>² = .497, <em>F</em>(1, 158) = 158.10, <em>p</em> &lt; .001. Adding three additional predictors — fertilizer application, temperature, and soil pH — produced a multiple regression model that was also statistically significant, <em>F</em>(4, 155) = 70.30, <em>p</em> &lt; .001, and explained a larger proportion of variance in yield, <em>R</em>² = .64, adjusted <em>R</em>² = .636.</p>
<p>The increase in adjusted <em>R</em>² from .497 to .636 indicates that the additional predictors accounted for meaningful variance in yield beyond rainfall alone, rather than merely adding noise (adjusted <em>R</em>², unlike <em>R</em>², penalizes the inclusion of uninformative predictors, making it the more appropriate statistic for comparing models of different sizes). This is further supported by the reduction in residual standard error from 333.1 to 283.5 kg/hectare, reflecting improved prediction accuracy.</p>
<p>Examining individual predictors in the multiple regression model, rainfall remained a strong, statistically significant positive predictor of yield, <em>b</em> = 2.34, <em>SE</em> = 0.16, <em>t</em>(155) = 14.46, <em>p</em> &lt; .001, with a coefficient nearly identical to its estimate in the simple regression (<em>b</em> = 2.37), suggesting its effect on yield is robust to the inclusion of other variables. Fertilizer application was also a significant positive predictor, <em>b</em> = 2.53, <em>SE</em> = 0.60, <em>t</em>(155) = 4.25, <em>p</em> &lt; .001, as was soil pH, <em>b</em> = 278.49, <em>SE</em> = 44.70, <em>t</em>(155) = 6.23, <em>p</em> &lt; .001, which showed the largest standardized influence relative to its measurement scale. Temperature, however, was not a statistically significant predictor in this model, <em>b</em> = −0.64, <em>SE</em> = 7.70, <em>t</em>(155) = −0.08, <em>p</em> = .934.</p>
<p>Let’s predict check the RMSE (Root Mean Squared Error):</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb137"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb137-1"><a href="#cb137-1" aria-hidden="true" tabindex="-1"></a>pred_multi <span class="ot">&lt;-</span> <span class="fu">predict</span>(lm_multiple, <span class="at">newdata =</span> test)</span>
<span id="cb137-2"><a href="#cb137-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sqrt</span>(<span class="fu">mean</span>((pred_multi <span class="sc">-</span> test<span class="sc">$</span>yield_kg_ha)<span class="sc">^</span><span class="dv">2</span>))   <span class="co"># test RMSE</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 372.6435</code></pre>
</div>
</div>
<p>The test RMSE of 372.64 kg/hectare represents the typical magnitude of error when the multiple regression model predicts crop yield on <strong>data it has not seen before</strong> (the held-out test set). In other words, on average, the model’s yield predictions deviate from actual yield by roughly 372.64 kg/hectare.</p>
<ul>
<li><p>The training-set residual standard error was 283.5 kg/hectare — noticeably lower than the test RMSE of 372.64.</p></li>
<li><p>This gap (283.5 vs.&nbsp;372.64) is a signal worth flagging: the model fits the training data better than it generalizes to new data. Some of this is expected (models almost always perform somewhat worse on unseen data), but a gap this size also lines up with what you found in the coefficient output — temperature was included as a plain linear term even though its true relationship with yield is quadratic (peaking at an optimal temperature). Because the model can’t capture that curvature, it likely makes systematically larger errors on test observations with temperatures far from the training set’s typical range, inflating the test RMSE.</p></li>
<li><p>To assess whether 372.64 kg/hectare is “good” or “bad,” it should be compared against the scale of the outcome itself — e.g., as a percentage of mean yield (mean(train$yield_kg_ha) would give you that denominator). A RMSE that’s small relative to typical yield (say, under 10%) suggests reasonably useful predictions for advisory purposes; one that’s large relative to typical yield suggests the model isn’t precise enough to act on without caution.</p></li>
<li><p>This is exactly the kind of gap the <strong>polynomial regression</strong> step (correctly modeling temperature’s curvature) should help close — comparing this multiple-regression test RMSE against the polynomial model’s test RMSE would be a natural next check, and a good addition to your assignment’s Part C if you want students to explicitly connect “which model generalizes best” rather than just “which model fits training data best.”</p></li>
</ul>
</section>
<section id="polynomial-regression" class="level3" data-number="6.5.5">
<h3 data-number="6.5.5" class="anchored" data-anchor-id="polynomial-regression"><span class="header-section-number">6.5.5</span> POLYNOMIAL REGRESSION</h3>
<p>We build polynomial model that Captures a curved relationship - here, yield peaks at an OPTIMAL temperature rather than rising or falling monotonically.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb139"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb139-1"><a href="#cb139-1" aria-hidden="true" tabindex="-1"></a>lm_poly <span class="ot">&lt;-</span> <span class="fu">lm</span>(yield_kg_ha <span class="sc">~</span> <span class="fu">poly</span>(temperature_C, <span class="dv">2</span>) <span class="sc">+</span> rainfall_mm <span class="sc">+</span> fertilizer_kg <span class="sc">+</span> soil_ph,</span>
<span id="cb139-2"><a href="#cb139-2" aria-hidden="true" tabindex="-1"></a>              <span class="at">data =</span> train)</span>
<span id="cb139-3"><a href="#cb139-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm_poly)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = yield_kg_ha ~ poly(temperature_C, 2) + rainfall_mm + 
    fertilizer_kg + soil_ph, data = train)

Residuals:
    Min      1Q  Median      3Q     Max 
-521.34 -134.14    1.29  128.03  513.63 

Coefficients:
                          Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)              2113.7362   231.3758   9.136 3.54e-16 ***
poly(temperature_C, 2)1    11.1288   211.0545   0.053    0.958    
poly(temperature_C, 2)2 -2412.8212   209.6024 -11.511  &lt; 2e-16 ***
rainfall_mm                 2.4653     0.1195  20.638  &lt; 2e-16 ***
fertilizer_kg               2.5721     0.4383   5.868 2.61e-08 ***
soil_ph                   291.5119    32.8943   8.862 1.81e-15 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 208.6 on 154 degrees of freedom
Multiple R-squared:  0.809, Adjusted R-squared:  0.8028 
F-statistic: 130.5 on 5 and 154 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb141"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb141-1"><a href="#cb141-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(train, <span class="fu">aes</span>(temperature_C, yield_kg_ha)) <span class="sc">+</span></span>
<span id="cb141-2"><a href="#cb141-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.4</span>) <span class="sc">+</span></span>
<span id="cb141-3"><a href="#cb141-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">formula =</span> y <span class="sc">~</span> <span class="fu">poly</span>(x, <span class="dv">2</span>), <span class="at">color =</span> <span class="st">"darkorange"</span>) <span class="sc">+</span></span>
<span id="cb141-4"><a href="#cb141-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Polynomial Regression: Yield vs. Temperature (degree 2)"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="block-II-unit-1_files/figure-html/unnamed-chunk-35-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>A polynomial regression model was estimated to test whether allowing temperature a curved (quadratic) relationship with yield would improve on the purely linear multiple regression model. The polynomial model was statistically significant, <em>F</em>(5, 154) = 130.50, <em>p</em> &lt; .001, and explained substantially more variance in yield than the linear multiple regression model, <em>R</em>² = .809, adjusted <em>R</em>² = .803, compared to <em>R</em>² = .645, adjusted <em>R</em>² = .636 previously.</p>
<p>The quadratic term for temperature was highly significant, <em>b</em> = −2412.82, <em>SE</em> = 209.60, <em>t</em>(154) = −11.51, <em>p</em> &lt; .001, while the linear temperature term was not, <em>b</em> = 11.13, <em>SE</em> = 211.05, <em>t</em>(154) = 0.05, <em>p</em> = .958. This pattern confirms what the earlier linear model’s non-significant temperature coefficient had obscured: temperature does meaningfully affect yield, but through a <strong>curved, not straight-line, relationship</strong> — consistent with an agronomic optimum temperature, where yield is highest at a moderate temperature and declines when conditions are either too cool or too hot. The negative sign on the squared term indicates an inverted-U (concave-down) curve, as expected.</p>
<p>Rainfall, <em>b</em> = 2.47, <em>SE</em> = 0.12, <em>t</em>(154) = 20.64, <em>p</em> &lt; .001, fertilizer, <em>b</em> = 2.57, <em>SE</em> = 0.44, <em>t</em>(154) = 5.87, <em>p</em> &lt; .001, and soil pH, <em>b</em> = 291.51, <em>SE</em> = 32.89, <em>t</em>(154) = 8.86, <em>p</em> &lt; .001, all remained significant positive predictors, with coefficient estimates very similar to the linear multiple regression model — indicating their linear effects on yield were already well-captured and are not confounded with temperature’s curvature.</p>
<p>The residual standard error also dropped notably, from 283.5 kg/hectare (linear multiple regression) to 208.6 kg/hectare (polynomial), reflecting a considerably tighter fit to the training data once temperature’s true functional form was correctly specified.</p>
<p><strong>Practical takeaway:</strong> This is a clean illustration of a common modeling mistake — a predictor can appear “non-significant” in a linear model not because it doesn’t matter, but because the model was given the wrong functional form to detect it. Once quadratic curvature was allowed, temperature emerged as one of the most important predictors in the model (via its squared term).</p>
<p>One useful next step for your assignment: compute this model’s <strong>test RMSE</strong> (the same way as before, using <code>predict(lm_poly, newdata = test)</code>) and compare it directly against the 372.64 kg/hectare from the linear multiple regression — that comparison will tell students concretely whether correctly modeling temperature’s curvature also improves <em>generalization</em>, not just training fit.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb142"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb142-1"><a href="#cb142-1" aria-hidden="true" tabindex="-1"></a>preds_poly <span class="ot">=</span> <span class="fu">predict</span>(lm_poly, <span class="at">newdata =</span> test)</span>
<span id="cb142-2"><a href="#cb142-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb142-3"><a href="#cb142-3" aria-hidden="true" tabindex="-1"></a><span class="fu">sqrt</span>(<span class="fu">mean</span>((preds_poly <span class="sc">-</span> test<span class="sc">$</span>yield_kg_ha)<span class="sc">^</span><span class="dv">2</span>))   <span class="co"># test RMSE</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 203.5892</code></pre>
</div>
</div>
<p>We can see that RMSE is now reduced to 203.59 from 372.64. There is an improvement in accuracy of the model.</p>
</section>
<section id="nonlinear-regression-nls" class="level3" data-number="6.5.6">
<h3 data-number="6.5.6" class="anchored" data-anchor-id="nonlinear-regression-nls"><span class="header-section-number">6.5.6</span> NONLINEAR REGRESSION (nls)</h3>
<p>Now, we fit a nonlinear functional FORM (not just apolynomial in the linear-model framework)here a Michaelis-Menten style diminishing-returns curve for fertilizer using yield = Vmax * fertilizer / (K + fertilizer).</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb144"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb144-1"><a href="#cb144-1" aria-hidden="true" tabindex="-1"></a>nls_fert <span class="ot">&lt;-</span> <span class="fu">nls</span>(</span>
<span id="cb144-2"><a href="#cb144-2" aria-hidden="true" tabindex="-1"></a>  yield_kg_ha <span class="sc">~</span> Vmax <span class="sc">*</span> fertilizer_kg <span class="sc">/</span> (K <span class="sc">+</span> fertilizer_kg),</span>
<span id="cb144-3"><a href="#cb144-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">data  =</span> train,</span>
<span id="cb144-4"><a href="#cb144-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">start =</span> <span class="fu">list</span>(<span class="at">Vmax =</span> <span class="dv">6000</span>, <span class="at">K =</span> <span class="dv">50</span>)   <span class="co"># starting guesses required for nls</span></span>
<span id="cb144-5"><a href="#cb144-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb144-6"><a href="#cb144-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(nls_fert)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Formula: yield_kg_ha ~ Vmax * fertilizer_kg/(K + fertilizer_kg)

Parameters:
      Estimate Std. Error t value Pr(&gt;|t|)    
Vmax 6375.7537    73.5154  86.727  &lt; 2e-16 ***
K       2.0904     0.6778   3.084  0.00241 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 455.9 on 158 degrees of freedom

Number of iterations to convergence: 5 
Achieved convergence tolerance: 3.413e-07</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb146"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb146-1"><a href="#cb146-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(train, <span class="fu">aes</span>(fertilizer_kg, yield_kg_ha)) <span class="sc">+</span></span>
<span id="cb146-2"><a href="#cb146-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.4</span>) <span class="sc">+</span></span>
<span id="cb146-3"><a href="#cb146-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> <span class="fu">predict</span>(nls_fert)), <span class="at">color =</span> <span class="st">"forestgreen"</span>, <span class="at">linewidth =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb146-4"><a href="#cb146-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Nonlinear Regression: Diminishing Returns on Fertilizer"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="block-II-unit-1_files/figure-html/unnamed-chunk-37-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="stepwise-regression" class="level3" data-number="6.5.7">
<h3 data-number="6.5.7" class="anchored" data-anchor-id="stepwise-regression"><span class="header-section-number">6.5.7</span> STEPWISE REGRESSION</h3>
<p>When we build model we use a set of predictors. All predictors do not contribute to the model and still create noise and increases variance. Here, we use STEPWISE REGRESSION which automatically selects a subset of predictors by adding/removing predictors to optimize AIC (lower = better trade-off of fit vs.&nbsp;complexity).</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb147"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb147-1"><a href="#cb147-1" aria-hidden="true" tabindex="-1"></a>full_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(yield_kg_ha <span class="sc">~</span> rainfall_mm <span class="sc">+</span> fertilizer_kg <span class="sc">+</span> temperature_C <span class="sc">+</span> soil_ph,</span>
<span id="cb147-2"><a href="#cb147-2" aria-hidden="true" tabindex="-1"></a>                  <span class="at">data =</span> train)</span>
<span id="cb147-3"><a href="#cb147-3" aria-hidden="true" tabindex="-1"></a>null_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(yield_kg_ha <span class="sc">~</span> <span class="dv">1</span>, <span class="at">data =</span> train)</span>
<span id="cb147-4"><a href="#cb147-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb147-5"><a href="#cb147-5" aria-hidden="true" tabindex="-1"></a>step_model <span class="ot">&lt;-</span> stats<span class="sc">::</span><span class="fu">step</span>(</span>
<span id="cb147-6"><a href="#cb147-6" aria-hidden="true" tabindex="-1"></a>  null_model,</span>
<span id="cb147-7"><a href="#cb147-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">scope =</span> <span class="fu">list</span>(<span class="at">lower =</span> null_model, <span class="at">upper =</span> full_model),</span>
<span id="cb147-8"><a href="#cb147-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">direction =</span> <span class="st">"both"</span>,   <span class="co"># "forward", "backward", or "both"</span></span>
<span id="cb147-9"><a href="#cb147-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">trace =</span> <span class="cn">FALSE</span></span>
<span id="cb147-10"><a href="#cb147-10" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb147-11"><a href="#cb147-11" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(step_model)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = yield_kg_ha ~ rainfall_mm + soil_ph + fertilizer_kg, 
    data = train)

Residuals:
    Min      1Q  Median      3Q     Max 
-1022.2  -185.3    39.2   185.4   616.6 

Coefficients:
               Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   2299.2125   310.8933   7.396 8.11e-12 ***
rainfall_mm      2.3401     0.1598  14.641  &lt; 2e-16 ***
soil_ph        278.7416    44.4501   6.271 3.37e-09 ***
fertilizer_kg    2.5317     0.5936   4.265 3.45e-05 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 282.6 on 156 degrees of freedom
Multiple R-squared:  0.6446,    Adjusted R-squared:  0.6378 
F-statistic: 94.33 on 3 and 156 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb149"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb149-1"><a href="#cb149-1" aria-hidden="true" tabindex="-1"></a><span class="fu">formula</span>(step_model)   <span class="co"># which predictors survived</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>yield_kg_ha ~ rainfall_mm + soil_ph + fertilizer_kg</code></pre>
</div>
</div>
<p>A stepwise regression procedure (bidirectional selection based on AIC) was conducted to identify the subset of predictors that best explained crop yield, starting from an intercept-only model and considering rainfall, fertilizer, temperature, and soil pH as candidate predictors. The procedure selected a final model retaining rainfall, soil pH, and fertilizer, while <strong>removing temperature entirely</strong> from the model.</p>
<p>The selected model was statistically significant, <em>F</em>(3, 156) = 94.33, <em>p</em> &lt; .001, and explained approximately 64.5% of the variance in yield, <em>R</em>² = .645, adjusted <em>R</em>² = .638. Rainfall was the strongest predictor, <em>b</em> = 2.34, <em>SE</em> = 0.16, <em>t</em>(156) = 14.64, <em>p</em> &lt; .001, followed by soil pH, <em>b</em> = 278.74, <em>SE</em> = 44.45, <em>t</em>(156) = 6.27, <em>p</em> &lt; .001, and fertilizer, <em>b</em> = 2.53, <em>SE</em> = 0.59, <em>t</em>(156) = 4.27, <em>p</em> &lt; .001. All three retained predictors were significant positive predictors of yield.</p>
<p><strong>Comparison to the full linear multiple regression model:</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Model</th>
<th>Predictors</th>
<th>Adjusted R²</th>
<th>Residual SE</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Full linear multiple</td>
<td>rainfall + fertilizer + temperature + soil pH</td>
<td>.636</td>
<td>283.5</td>
</tr>
<tr class="even">
<td>Stepwise-selected</td>
<td>rainfall + fertilizer + soil pH</td>
<td>.638</td>
<td>282.6</td>
</tr>
</tbody>
</table>
<p>Notably, the stepwise model achieves a <em>marginally higher</em> adjusted R² (.638 vs.&nbsp;.636) and lower residual standard error (282.6 vs.&nbsp;283.5) than the full model — <strong>despite dropping a predictor</strong>. This is expected: adjusted R² penalizes unnecessary predictors, and since temperature’s <em>linear</em> term was non-significant in the full model (<em>p</em> = .934, from your earlier output), removing it slightly improves the fit efficiency without sacrificing explanatory power.</p>
<p><strong>Important caveat worth flagging (especially for a student assignment):</strong> this result illustrates a key limitation of stepwise selection rather than a genuine insight about temperature’s importance. Temperature was correctly dropped <em>as a linear term</em>, but your polynomial regression model showed temperature’s quadratic term was highly significant (<em>p</em> &lt; .001) and substantially improved fit (adjusted R² = .803). Stepwise selection using <code>step()</code> only ever considered rainfall, fertilizer, temperature, and soil pH as <strong>linear terms</strong> — it never had the opportunity to discover the curved relationship, because <code>poly(temperature_C, 2)</code> was never in its candidate scope. This is a classic pitfall of stepwise/AIC-based selection: it can only select among the functional forms you explicitly offer it, and will confidently discard a genuinely important predictor if its true effect doesn’t match the form tested.</p>
<p><strong>Practical takeaway:</strong> stepwise regression is useful for pruning redundant linear predictors efficiently, but it is not a substitute for exploring nonlinear relationships first (via EDA plots or domain knowledge) — a variable dropped by stepwise selection may still be highly important if given the right functional form, as shown here.</p>
</section>
<section id="ridge-regression" class="level3" data-number="6.5.8">
<h3 data-number="6.5.8" class="anchored" data-anchor-id="ridge-regression"><span class="header-section-number">6.5.8</span> RIDGE REGRESSION</h3>
<p>RIDGE REGRESSION Shrinks ALL coefficients toward zero (L2 penalty) - keeps every predictor but reduces overfitting/multicollinearity impact. Let’s check how it works now:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb151"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb151-1"><a href="#cb151-1" aria-hidden="true" tabindex="-1"></a>x_train <span class="ot">&lt;-</span> <span class="fu">as.matrix</span>(train[, <span class="fu">c</span>(<span class="st">"rainfall_mm"</span>, <span class="st">"fertilizer_kg"</span>, <span class="st">"temperature_C"</span>, <span class="st">"soil_ph"</span>)])</span>
<span id="cb151-2"><a href="#cb151-2" aria-hidden="true" tabindex="-1"></a>y_train <span class="ot">&lt;-</span> train<span class="sc">$</span>yield_kg_ha</span>
<span id="cb151-3"><a href="#cb151-3" aria-hidden="true" tabindex="-1"></a>x_test  <span class="ot">&lt;-</span> <span class="fu">as.matrix</span>(test[,  <span class="fu">c</span>(<span class="st">"rainfall_mm"</span>, <span class="st">"fertilizer_kg"</span>, <span class="st">"temperature_C"</span>, <span class="st">"soil_ph"</span>)])</span>
<span id="cb151-4"><a href="#cb151-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb151-5"><a href="#cb151-5" aria-hidden="true" tabindex="-1"></a>ridge_cv <span class="ot">&lt;-</span> <span class="fu">cv.glmnet</span>(x_train, y_train, <span class="at">alpha =</span> <span class="dv">0</span>)   <span class="co"># alpha = 0 -&gt; ridge</span></span>
<span id="cb151-6"><a href="#cb151-6" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(ridge_cv)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="block-II-unit-1_files/figure-html/unnamed-chunk-39-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb152"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb152-1"><a href="#cb152-1" aria-hidden="true" tabindex="-1"></a>best_lambda_ridge <span class="ot">&lt;-</span> ridge_cv<span class="sc">$</span>lambda.min</span>
<span id="cb152-2"><a href="#cb152-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb152-3"><a href="#cb152-3" aria-hidden="true" tabindex="-1"></a>ridge_model <span class="ot">&lt;-</span> <span class="fu">glmnet</span>(x_train, y_train, <span class="at">alpha =</span> <span class="dv">0</span>, <span class="at">lambda =</span> best_lambda_ridge)</span>
<span id="cb152-4"><a href="#cb152-4" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(ridge_model)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>5 x 1 sparse Matrix of class "dgCMatrix"
                       s0
(Intercept)   2587.943930
rainfall_mm      2.182658
fertilizer_kg    2.378863
temperature_C   -1.634813
soil_ph        262.315045</code></pre>
</div>
</div>
<p>Let’s evaluate RIDGE MODEL:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb154"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb154-1"><a href="#cb154-1" aria-hidden="true" tabindex="-1"></a>pred_ridge <span class="ot">&lt;-</span> <span class="fu">predict</span>(ridge_model, <span class="at">newx =</span> x_test)</span>
<span id="cb154-2"><a href="#cb154-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sqrt</span>(<span class="fu">mean</span>((pred_ridge <span class="sc">-</span> test<span class="sc">$</span>yield_kg_ha)<span class="sc">^</span><span class="dv">2</span>))   <span class="co"># test RMSE</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 383.9022</code></pre>
</div>
</div>
</section>
<section id="lasso-regression" class="level3" data-number="6.5.9">
<h3 data-number="6.5.9" class="anchored" data-anchor-id="lasso-regression"><span class="header-section-number">6.5.9</span> LASSO REGRESSION</h3>
<p>LASSO REGRESSION shrinks coefficients toward zero AND can set some exactly to zero (L1 penalty) - performs automatic variable selection.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb156"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb156-1"><a href="#cb156-1" aria-hidden="true" tabindex="-1"></a>lasso_cv <span class="ot">&lt;-</span> <span class="fu">cv.glmnet</span>(x_train, y_train, <span class="at">alpha =</span> <span class="dv">1</span>)   <span class="co"># alpha = 1 -&gt; lasso</span></span>
<span id="cb156-2"><a href="#cb156-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(lasso_cv)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="block-II-unit-1_files/figure-html/unnamed-chunk-41-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb157"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb157-1"><a href="#cb157-1" aria-hidden="true" tabindex="-1"></a>best_lambda_lasso <span class="ot">&lt;-</span> lasso_cv<span class="sc">$</span>lambda.min</span>
<span id="cb157-2"><a href="#cb157-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb157-3"><a href="#cb157-3" aria-hidden="true" tabindex="-1"></a>lasso_model <span class="ot">&lt;-</span> <span class="fu">glmnet</span>(x_train, y_train, <span class="at">alpha =</span> <span class="dv">1</span>, <span class="at">lambda =</span> best_lambda_lasso)</span>
<span id="cb157-4"><a href="#cb157-4" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(lasso_model)   <span class="co"># predictors shrunk to exactly 0 are effectively dropped</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>5 x 1 sparse Matrix of class "dgCMatrix"
                       s0
(Intercept)   2616.718547
rainfall_mm      2.221523
fertilizer_kg    2.116091
temperature_C    .       
soil_ph        249.681922</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb159"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb159-1"><a href="#cb159-1" aria-hidden="true" tabindex="-1"></a>pred_lasso <span class="ot">&lt;-</span> <span class="fu">predict</span>(lasso_model, <span class="at">newx =</span> x_test)</span>
<span id="cb159-2"><a href="#cb159-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sqrt</span>(<span class="fu">mean</span>((pred_lasso <span class="sc">-</span> test<span class="sc">$</span>yield_kg_ha)<span class="sc">^</span><span class="dv">2</span>))   <span class="co"># test RMSE</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 380.7707</code></pre>
</div>
</div>
</section>
<section id="quantile-regression" class="level3" data-number="6.5.10">
<h3 data-number="6.5.10" class="anchored" data-anchor-id="quantile-regression"><span class="header-section-number">6.5.10</span> QUANTILE REGRESSION</h3>
<p>Models a specific PERCENTILE of the outcome (not just the mean) - e.g.&nbsp;the 10th percentile is useful for “worst-case” yield planning, the 90th for best-case</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb161"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb161-1"><a href="#cb161-1" aria-hidden="true" tabindex="-1"></a>qr_median <span class="ot">&lt;-</span> <span class="fu">rq</span>(yield_kg_ha <span class="sc">~</span> rainfall_mm <span class="sc">+</span> fertilizer_kg <span class="sc">+</span> temperature_C <span class="sc">+</span> soil_ph,</span>
<span id="cb161-2"><a href="#cb161-2" aria-hidden="true" tabindex="-1"></a>                 <span class="at">data =</span> train, <span class="at">tau =</span> <span class="fl">0.5</span>)   <span class="co"># tau = 0.5 -&gt; median regression</span></span>
<span id="cb161-3"><a href="#cb161-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(qr_median)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call: rq(formula = yield_kg_ha ~ rainfall_mm + fertilizer_kg + temperature_C + 
    soil_ph, tau = 0.5, data = train)

tau: [1] 0.5

Coefficients:
              coefficients lower bd   upper bd  
(Intercept)   2258.38498    734.06630 3093.08693
rainfall_mm      2.28506      2.03619    2.63899
fertilizer_kg    2.49500      0.85012    3.42591
temperature_C    5.39328    -19.95405   30.27147
soil_ph        275.80216    221.09104  369.59808</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb163"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb163-1"><a href="#cb163-1" aria-hidden="true" tabindex="-1"></a>qr_low  <span class="ot">&lt;-</span> <span class="fu">rq</span>(yield_kg_ha <span class="sc">~</span> rainfall_mm <span class="sc">+</span> fertilizer_kg, <span class="at">data =</span> train, <span class="at">tau =</span> <span class="fl">0.10</span>)</span>
<span id="cb163-2"><a href="#cb163-2" aria-hidden="true" tabindex="-1"></a>qr_high <span class="ot">&lt;-</span> <span class="fu">rq</span>(yield_kg_ha <span class="sc">~</span> rainfall_mm <span class="sc">+</span> fertilizer_kg, <span class="at">data =</span> train, <span class="at">tau =</span> <span class="fl">0.90</span>)</span>
<span id="cb163-3"><a href="#cb163-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb163-4"><a href="#cb163-4" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(train, <span class="fu">aes</span>(rainfall_mm, yield_kg_ha)) <span class="sc">+</span></span>
<span id="cb163-5"><a href="#cb163-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.3</span>) <span class="sc">+</span></span>
<span id="cb163-6"><a href="#cb163-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_quantile</span>(<span class="at">quantiles =</span> <span class="fu">c</span>(<span class="fl">0.1</span>, <span class="fl">0.5</span>, <span class="fl">0.9</span>), <span class="at">color =</span> <span class="st">"purple"</span>) <span class="sc">+</span></span>
<span id="cb163-7"><a href="#cb163-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Quantile Regression: 10th / 50th / 90th Percentile Yield"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Smoothing formula not specified. Using: y ~ x</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="block-II-unit-1_files/figure-html/unnamed-chunk-42-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="logistic-regression" class="level3" data-number="6.5.11">
<h3 data-number="6.5.11" class="anchored" data-anchor-id="logistic-regression"><span class="header-section-number">6.5.11</span> LOGISTIC REGRESSION</h3>
<p>Now we want to classify the yield as Good For a BINARY outcome - here, whether yield is “good”(1) or “bad” (0).</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb165"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb165-1"><a href="#cb165-1" aria-hidden="true" tabindex="-1"></a>log_model <span class="ot">&lt;-</span> <span class="fu">glm</span>(good_yield <span class="sc">~</span> rainfall_mm <span class="sc">+</span> fertilizer_kg <span class="sc">+</span> temperature_C <span class="sc">+</span> soil_ph,</span>
<span id="cb165-2"><a href="#cb165-2" aria-hidden="true" tabindex="-1"></a>                  <span class="at">data =</span> train, <span class="at">family =</span> binomial)</span>
<span id="cb165-3"><a href="#cb165-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(log_model)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = good_yield ~ rainfall_mm + fertilizer_kg + temperature_C + 
    soil_ph, family = binomial, data = train)

Coefficients:
                Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)   -25.775522   5.338626  -4.828 1.38e-06 ***
rainfall_mm     0.015777   0.002649   5.956 2.59e-09 ***
fertilizer_kg   0.014366   0.006125   2.345    0.019 *  
temperature_C  -0.076273   0.075452  -1.011    0.312    
soil_ph         2.196929   0.519530   4.229 2.35e-05 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 221.78  on 159  degrees of freedom
Residual deviance: 130.09  on 155  degrees of freedom
AIC: 140.09

Number of Fisher Scoring iterations: 6</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb167"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb167-1"><a href="#cb167-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Predicted probabilities and classification on test data</span></span>
<span id="cb167-2"><a href="#cb167-2" aria-hidden="true" tabindex="-1"></a>pred_prob  <span class="ot">&lt;-</span> <span class="fu">predict</span>(log_model, <span class="at">newdata =</span> test, <span class="at">type =</span> <span class="st">"response"</span>)</span>
<span id="cb167-3"><a href="#cb167-3" aria-hidden="true" tabindex="-1"></a>pred_class <span class="ot">&lt;-</span> <span class="fu">factor</span>(<span class="fu">ifelse</span>(pred_prob <span class="sc">&gt;</span> <span class="fl">0.5</span>, <span class="dv">1</span>, <span class="dv">0</span>))</span>
<span id="cb167-4"><a href="#cb167-4" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(<span class="at">Predicted =</span> pred_class, <span class="at">Actual =</span> test<span class="sc">$</span>good_yield)   <span class="co"># confusion matrix</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>         Actual
Predicted  0  1
        0 16  4
        1  5 15</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb169"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb169-1"><a href="#cb169-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(pred_class <span class="sc">==</span> test<span class="sc">$</span>good_yield)                       <span class="co"># accuracy</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.775</code></pre>
</div>
</div>
</section>
</section>
<section id="section" class="level2" data-number="6.6">
<h2 data-number="6.6" class="anchored" data-anchor-id="section"><span class="header-section-number">6.6</span> ============================================================</h2>
</section>
<section id="summary-when-to-use-which" class="level2" data-number="6.7">
<h2 data-number="6.7" class="anchored" data-anchor-id="summary-when-to-use-which"><span class="header-section-number">6.7</span> SUMMARY — When to use which</h2>
</section>
<section id="section-1" class="level2" data-number="6.8">
<h2 data-number="6.8" class="anchored" data-anchor-id="section-1"><span class="header-section-number">6.8</span> ============================================================</h2>
</section>
<section id="linear---one-predictor-straight-line-relationship" class="level2" data-number="6.9">
<h2 data-number="6.9" class="anchored" data-anchor-id="linear---one-predictor-straight-line-relationship"><span class="header-section-number">6.9</span> Linear - one predictor, straight-line relationship</h2>
</section>
<section id="multiple---several-predictors-each-additivelinear" class="level2" data-number="6.10">
<h2 data-number="6.10" class="anchored" data-anchor-id="multiple---several-predictors-each-additivelinear"><span class="header-section-number">6.10</span> Multiple - several predictors, each additive/linear</h2>
</section>
<section id="polynomial---curved-relationship-still-fit-within-lm-framework" class="level2" data-number="6.11">
<h2 data-number="6.11" class="anchored" data-anchor-id="polynomial---curved-relationship-still-fit-within-lm-framework"><span class="header-section-number">6.11</span> Polynomial - curved relationship still fit within lm() framework</h2>
</section>
<section id="nonlinearnls--true-nonlinear-functional-form-e.g.-saturation" class="level2" data-number="6.12">
<h2 data-number="6.12" class="anchored" data-anchor-id="nonlinearnls--true-nonlinear-functional-form-e.g.-saturation"><span class="header-section-number">6.12</span> Nonlinear(nls)- true nonlinear functional form (e.g.&nbsp;saturation,</h2>
</section>
<section id="growth-curves---you-must-specify-the-equation" class="level2" data-number="6.13">
<h2 data-number="6.13" class="anchored" data-anchor-id="growth-curves---you-must-specify-the-equation"><span class="header-section-number">6.13</span> growth curves) - you must specify the equation</h2>
</section>
<section id="stepwise---automatic-predictor-selection-via-aic" class="level2" data-number="6.14">
<h2 data-number="6.14" class="anchored" data-anchor-id="stepwise---automatic-predictor-selection-via-aic"><span class="header-section-number">6.14</span> Stepwise - automatic predictor selection via AIC</h2>
</section>
<section id="ridge---manycorrelated-predictors-keep-all-shrink-coefficients" class="level2" data-number="6.15">
<h2 data-number="6.15" class="anchored" data-anchor-id="ridge---manycorrelated-predictors-keep-all-shrink-coefficients"><span class="header-section-number">6.15</span> Ridge - many/correlated predictors, keep all, shrink coefficients</h2>
</section>
<section id="lasso---many-predictors-want-automatic-feature-selection" class="level2" data-number="6.16">
<h2 data-number="6.16" class="anchored" data-anchor-id="lasso---many-predictors-want-automatic-feature-selection"><span class="header-section-number">6.16</span> Lasso - many predictors, want automatic feature selection</h2>
</section>
<section id="quantile---care-about-a-specific-percentile-not-just-the-mean" class="level2" data-number="6.17">
<h2 data-number="6.17" class="anchored" data-anchor-id="quantile---care-about-a-specific-percentile-not-just-the-mean"><span class="header-section-number">6.17</span> Quantile - care about a specific percentile, not just the mean</h2>
</section>
<section id="e.g.-worst-casebest-case-yield-planning" class="level2" data-number="6.18">
<h2 data-number="6.18" class="anchored" data-anchor-id="e.g.-worst-casebest-case-yield-planning"><span class="header-section-number">6.18</span> (e.g.&nbsp;worst-case/best-case yield planning)</h2>
</section>
<section id="logistic---binary-outcome-successfailure-goodbad-yesno" class="level2" data-number="6.19">
<h2 data-number="6.19" class="anchored" data-anchor-id="logistic---binary-outcome-successfailure-goodbad-yesno"><span class="header-section-number">6.19</span> Logistic - binary outcome (success/failure, good/bad, yes/no)</h2>
</section>
<section id="section-2" class="level2" data-number="6.20">
<h2 data-number="6.20" class="anchored" data-anchor-id="section-2"><span class="header-section-number">6.20</span> ============================================================</h2>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./block-I-unit-2.html" class="pagination-link" aria-label="Block I Unit 2">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Block I Unit 2</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./block-II-unit-2.html" class="pagination-link" aria-label="Block II Unit 2">
        <span class="nav-page-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Block II Unit 2</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>